"""Mathematical reasoning engine for Genesis.

This module gives Genesis the ability to DO mathematics, not just know
about it. It provides four capabilities:

1. **Computation** — parse and evaluate arithmetic expressions
2. **Symbolic manipulation** — solve equations by applying
   transformation rules
3. **Proof construction** — verify statements by computation,
   expansion, and templated proofs
4. **Discovery** — generate examples, detect patterns, form and test
   conjectures

## Architecture: computational substrate with configurable rules

The engines (parser, evaluator, solver, discovery) are code — they
are the "hardware" of mathematical reasoning. The RULES they apply
(commutativity, identity, balance, quadratic formula) can be either
hardcoded (default, backward compatible) or gated by the concept
network via ``MathRuleRegistry``.

When ``try_math()`` is called with a concept network, it builds a
``MathRuleRegistry`` that checks which math concepts Genesis has
learned. Only rules whose corresponding concepts exist in the network
(with sufficient confidence) are applied. This means training Genesis
on "the additive identity says that a + 0 = a" enables that rule in
the simplifier.

Without a concept network, all rules are enabled (backward compatible).

## What's genuine vs templated

- **Computation** (parser + evaluator): genuine — parses and evaluates
  real expressions with operator precedence, functions, variables.
- **Equation solving**: genuine — extracts polynomial coefficients,
  applies the quadratic formula, handles complex roots.
- **Discovery**: genuine — generates primes (Sieve of Eratosthenes),
  verifies parity/Goldbach/twin-prime patterns by actual computation.
- **Proof by computation**: genuine — evaluates both sides of an
  equation and checks equality.
- **Proof by expansion**: genuine — expands and collects terms on
  both sides, checks structural equality.
- **Even/odd proofs**: templated — hardcoded proof steps, not
  generated by a proof search algorithm.
- **Induction proof**: templated — hardcoded for the specific case
  ``1 + 2 + ... + n = n(n+1)/2``.
"""

from __future__ import annotations

import logging
import math
import re
from collections.abc import Callable
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, ClassVar

logger = logging.getLogger(__name__)

# ═══════════════════════════════════════════════════════════════════════
# Part 1: Expression Parser
# ═══════════════════════════════════════════════════════════════════════


class TokenType(Enum):
    """Types of tokens produced by the math expression tokenizer."""

    NUMBER = "number"
    IDENT = "ident"  # variable or function name
    PLUS = "+"
    MINUS = "-"
    STAR = "*"
    SLASH = "/"
    CARET = "^"
    LPAREN = "("
    RPAREN = ")"
    EQ = "="
    LT = "<"
    GT = ">"
    LE = "<="
    GE = ">="
    NE = "!="
    COMMA = ","
    EOF = "eof"


@dataclass(slots=True)
class Token:
    """A single token from the math expression tokenizer."""

    type: TokenType
    value: str
    pos: int


_SINGLE_CHAR_OPS = {
    "+": TokenType.PLUS,
    "-": TokenType.MINUS,
    "*": TokenType.STAR,
    "/": TokenType.SLASH,
    "^": TokenType.CARET,
    "(": TokenType.LPAREN,
    ")": TokenType.RPAREN,
    "=": TokenType.EQ,
    "<": TokenType.LT,
    ">": TokenType.GT,
    ",": TokenType.COMMA,
}

_MULTI_CHAR_OPS = {
    "<=": TokenType.LE,
    ">=": TokenType.GE,
    "!=": TokenType.NE,
    "==": TokenType.EQ,
}


def _scan_number(text: str, i: int, tokens: list[Token]) -> int:
    """Scan a numeric literal (with scientific notation) and append a NUMBER token.

    Also inserts an implicit-multiplication STAR when the number is
    immediately followed by a variable/function name.
    Returns the new scan index.
    """
    start = i
    while i < len(text) and (text[i].isdigit() or text[i] == "."):
        i += 1
    # Scientific notation
    if i < len(text) and text[i] in "eE":
        j = i + 1
        if j < len(text) and text[j] in "+-":
            j += 1
        if j < len(text) and text[j].isdigit():
            i = j
            while i < len(text) and text[i].isdigit():
                i += 1
    tokens.append(Token(TokenType.NUMBER, text[start:i], start))
    # Insert implicit multiplication: number followed by
    # variable or function (e.g., "2x" → "2 * x", "3sin" → "3 * sin")
    if i < len(text) and (text[i].isalpha() or text[i] == "_"):
        tokens.append(Token(TokenType.STAR, "*", i))
    return i


def _scan_ident(text: str, i: int, tokens: list[Token]) -> int:
    """Scan an identifier (variable/function name) and append an IDENT token.

    Inserts an implicit-multiplication STAR when the identifier is
    immediately followed by another variable or a number (but NOT
    before "(", which is a function call). Returns the new scan index.
    """
    start = i
    while i < len(text) and (text[i].isalnum() or text[i] == "_"):
        i += 1
    tokens.append(Token(TokenType.IDENT, text[start:i], start))
    # Insert implicit multiplication: variable followed by
    # number or another variable (e.g., "x2" → "x * 2",
    # "xy" → "x * y"). But NOT before "(" — that's a
    # function call (e.g., "sqrt(...)", "sin(...)"), not
    # multiplication.
    if i < len(text) and (text[i].isalnum() or text[i] == "_"):
        if text[i].isalpha() or text[i] == "_":
            # Variable followed by variable: x*y
            tokens.append(Token(TokenType.STAR, "*", i))
        elif text[i].isdigit():
            # Variable followed by number: x*2
            tokens.append(Token(TokenType.STAR, "*", i))
    return i


def tokenize(text: str) -> list[Token]:
    """Convert a math expression string into tokens."""
    tokens: list[Token] = []
    i = 0
    text = text.replace("×", "*").replace("÷", "/").replace("−", "-")
    # Handle sqrt(), abs(), etc. — keep function names as idents
    while i < len(text):
        c = text[i]
        if c.isspace():
            i += 1
            continue
        # Multi-character operators
        if text[i : i + 2] in _MULTI_CHAR_OPS:
            op = text[i : i + 2]
            tokens.append(Token(_MULTI_CHAR_OPS[op], op, i))
            i += 2
            continue
        # Single-character operators
        if c in _SINGLE_CHAR_OPS:
            tokens.append(Token(_SINGLE_CHAR_OPS[c], c, i))
            i += 1
            continue
        # Numbers (integers, decimals, fractions like 3/4 handled by parser)
        if c.isdigit() or (c == "." and i + 1 < len(text) and text[i + 1].isdigit()):
            i = _scan_number(text, i, tokens)
            continue
        # Identifiers (variables, function names, constants)
        if c.isalpha() or c == "_":
            i = _scan_ident(text, i, tokens)
            continue
        # Unknown character — skip it
        i += 1
    tokens.append(Token(TokenType.EOF, "", len(text)))
    return tokens


# AST node types
@dataclass
class Num:
    """AST node for a numeric literal."""

    value: float | int

    def __str__(self) -> str:
        """Render the numeric literal, dropping a trailing ``.0`` for floats."""
        if isinstance(self.value, float) and self.value.is_integer():
            return str(int(self.value))
        return str(self.value)


@dataclass
class Var:
    """AST node for a variable reference."""

    name: str

    def __str__(self) -> str:
        """Render the variable name."""
        return self.name


@dataclass
class BinOp:
    """AST node for a binary operation."""

    op: str  # +, -, *, /, ^
    left: Any
    right: Any

    def __str__(self) -> str:
        """Render the binary operation as ``left op right``."""
        return f"{self.left} {self.op} {self.right}"


@dataclass
class UnaryOp:
    """AST node for a unary operation."""

    op: str  # -, +
    operand: Any

    def __str__(self) -> str:
        """Render the unary operation as ``op operand``."""
        return f"{self.op}{self.operand}"


@dataclass
class FuncCall:
    """AST node for a function call."""

    name: str
    args: list[Any]

    def __str__(self) -> str:
        """Render the function call as ``name(arg, ...)``."""
        return f"{self.name}({', '.join(str(a) for a in self.args)})"


@dataclass
class Equation:
    """AST node for an equation or comparison."""

    left: Any
    right: Any
    comparator: str  # =, <, >, <=, >=, !=

    def __str__(self) -> str:
        """Render the equation as ``left comparator right``."""
        return f"{self.left} {self.comparator} {self.right}"


class ParseError(Exception):
    """Raised when the parser encounters invalid syntax."""

    pass


class Parser:
    """Recursive descent parser for mathematical expressions and equations."""

    # Operator precedence (higher = binds tighter)
    # Comparison operators (=, <, >, etc.) are NOT here — they're
    # handled by parse() to create Equation nodes, not BinOp nodes.
    _PRECEDENCE: ClassVar[dict] = {
        TokenType.PLUS: 2,
        TokenType.MINUS: 2,
        TokenType.STAR: 3,
        TokenType.SLASH: 3,
        TokenType.CARET: 4,
    }

    def __init__(self, tokens: list[Token]) -> None:
        """Initialize the math expression parser."""
        self.tokens = tokens
        self.pos = 0

    def peek(self) -> Token:
        """Return the current token without consuming it."""
        return self.tokens[self.pos]

    def advance(self) -> Token:
        """Consume and return the current token, advancing to the next."""
        t = self.tokens[self.pos]
        self.pos += 1
        return t

    def expect(self, tt: TokenType) -> Token:
        """Consume the current token if it matches *tt*, else raise ParseError."""
        t = self.peek()
        if t.type != tt:
            raise ParseError(f"Expected {tt.value}, got {t.value!r} at pos {t.pos}")
        return self.advance()

    def parse(self) -> Equation | Any:
        """Parse a full expression or equation."""
        left = self._parse_expr(0)

        t = self.peek()
        if t.type in (
            TokenType.EQ,
            TokenType.LT,
            TokenType.GT,
            TokenType.LE,
            TokenType.GE,
            TokenType.NE,
        ):
            comp = t.value
            self.advance()
            right = self._parse_expr(0)
            return Equation(left, right, comp)

        return left

    def _parse_expr(self, min_prec: int) -> Any:
        """Parse an expression with operator precedence (Pratt parsing)."""
        left = self._parse_unary()

        while True:
            t = self.peek()
            prec = self._PRECEDENCE.get(t.type, 0)
            if prec < min_prec or prec == 0:
                break
            op = t.value
            self.advance()
            right = self._parse_expr(prec + 1)
            left = BinOp(op, left, right)

        return left

    def _parse_unary(self) -> Any:
        """Parse a unary expression (leading +/- or primary)."""
        t = self.peek()
        if t.type == TokenType.MINUS:
            self.advance()
            operand = self._parse_unary()
            return UnaryOp("-", operand)
        if t.type == TokenType.PLUS:
            self.advance()
            return self._parse_unary()
        return self._parse_primary()

    def _parse_primary(self) -> Any:
        """Parse a primary expression (number, variable, parenthesized)."""
        t = self.peek()

        if t.type == TokenType.NUMBER:
            self.advance()
            raw = t.value
            if "." in raw or "e" in raw or "E" in raw:
                return Num(float(raw))
            return Num(int(raw))

        if t.type == TokenType.IDENT:
            self.advance()
            name = t.value
            # Check for function call
            if self.peek().type == TokenType.LPAREN:
                self.advance()  # consume (
                args: list[Any] = []
                if self.peek().type != TokenType.RPAREN:
                    args.append(self._parse_expr(0))
                    while self.peek().type == TokenType.COMMA:
                        self.advance()
                        args.append(self._parse_expr(0))
                self.expect(TokenType.RPAREN)
                return FuncCall(name, args)
            # Named constants
            if name.lower() == "pi":
                return Num(math.pi)
            if name.lower() == "e":
                return Num(math.e)
            if name.lower() == "infinity":
                return Num(math.inf)
            return Var(name)

        if t.type == TokenType.LPAREN:
            self.advance()
            expr = self._parse_expr(0)
            self.expect(TokenType.RPAREN)
            return expr

        raise ParseError(f"Unexpected token {t.value!r} at pos {t.pos}")


def parse_expression(text: str) -> Equation | Any:
    """Parse a math expression or equation from text."""
    tokens = tokenize(text)
    parser = Parser(tokens)
    return parser.parse()


# ═══════════════════════════════════════════════════════════════════════
# Part 2: Evaluator (Computation)
# ═══════════════════════════════════════════════════════════════════════

# Built-in functions — these are the computational substrate.
# Which functions exist is learned (stored in concept network as
# concepts like "sine", "cosine", "square root"). The actual
# computation is performed by the engine, like neurons firing.
_BUILTIN_FUNCTIONS: dict[str, Callable[..., Any]] = {
    "sqrt": math.sqrt,
    "abs": abs,
    "sin": math.sin,
    "cos": math.cos,
    "tan": math.tan,
    "log": math.log,
    "ln": math.log,
    "log10": math.log10,
    "log2": math.log2,
    "exp": math.exp,
    "floor": math.floor,
    "ceil": math.ceil,
    "round": round,
    "factorial": lambda n: math.factorial(int(n)),
    "gcd": lambda a, b: math.gcd(int(a), int(b)),
    "max": max,
    "min": min,
    "mod": lambda a, b: a % b,
    "pow": pow,
}


class EvalError(Exception):
    """Raised when an expression cannot be evaluated."""

    pass


def evaluate(node: Any, env: dict[str, float] | None = None) -> float | int:
    """Evaluate an expression tree to a numeric value.

    Args:
        node: AST node (Num, Var, BinOp, UnaryOp, FuncCall)
        env: variable bindings (name → value)

    Returns:
        Numeric result

    Raises:
        EvalError: if the expression can't be evaluated (unbound variable, etc.)
    """
    if env is None:
        env = {}

    if isinstance(node, Num):
        return node.value

    if isinstance(node, Var):
        if node.name in env:
            return env[node.name]
        raise EvalError(f"Unbound variable: {node.name}")

    if isinstance(node, UnaryOp):
        val = evaluate(node.operand, env)
        if node.op == "-":
            return -val
        return val

    if isinstance(node, BinOp):
        left = evaluate(node.left, env)
        right = evaluate(node.right, env)
        if node.op == "+":
            return left + right
        if node.op == "-":
            return left - right
        if node.op == "*":
            return left * right
        if node.op == "/":
            if right == 0:
                raise EvalError("Division by zero")
            return left / right
        if node.op == "^":
            try:
                return left**right
            except (OverflowError, ValueError, ZeroDivisionError) as e:
                raise EvalError(f"Cannot evaluate power: {e}") from e
        raise EvalError(f"Unknown operator: {node.op}")

    if isinstance(node, FuncCall):
        if node.name not in _BUILTIN_FUNCTIONS:
            raise EvalError(f"Unknown function: {node.name}")
        args = [evaluate(a, env) for a in node.args]
        try:
            return _BUILTIN_FUNCTIONS[node.name](*args)
        except (ValueError, OverflowError, ZeroDivisionError) as e:
            raise EvalError(f"Cannot evaluate {node.name}: {e}") from e

    raise EvalError(f"Cannot evaluate node type: {type(node).__name__}")


def format_number(n: float | int) -> str:
    """Format a number nicely for display."""
    if isinstance(n, float):
        if n.is_integer() and abs(n) < 1e15:
            return str(int(n))
        if math.isinf(n):
            return "infinity" if n > 0 else "-infinity"
        # Round to reasonable precision
        return f"{n:.6g}"
    return str(n)


# ═══════════════════════════════════════════════════════════════════════
# Part 3: Symbolic Manipulation (Equation Solving)
# ═══════════════════════════════════════════════════════════════════════


def collect_variables(node: Any) -> set[str]:
    """Find all variable names in an expression tree."""
    if isinstance(node, Var):
        return {node.name}
    if isinstance(node, BinOp):
        return collect_variables(node.left) | collect_variables(node.right)
    if isinstance(node, UnaryOp):
        return collect_variables(node.operand)
    if isinstance(node, FuncCall):
        result: set[str] = set()
        for arg in node.args:
            result |= collect_variables(arg)
        return result
    return set()


def substitute(node: Any, env: dict[str, Any]) -> Any:
    """Substitute variables in an expression tree with values/expressions."""
    if isinstance(node, Num):
        return node
    if isinstance(node, Var):
        if node.name in env:
            val = env[node.name]
            if isinstance(val, (int, float)):
                return Num(val)
            return val
        return node
    if isinstance(node, BinOp):
        return BinOp(node.op, substitute(node.left, env), substitute(node.right, env))
    if isinstance(node, UnaryOp):
        return UnaryOp(node.op, substitute(node.operand, env))
    if isinstance(node, FuncCall):
        return FuncCall(node.name, [substitute(a, env) for a in node.args])
    return node


# ─── Math rule registry ────────────────────────────────────────

# All available simplification rules. When no concept network is
# provided, all rules are enabled (backward compatible).
_ALL_RULES: frozenset[str] = frozenset(
    {
        "additive_identity",
        "additive_inverse",
        "subtract_zero",
        "subtract_self",
        "multiplicative_zero",
        "multiplicative_identity",
        "multiplicative_inverse",
        "divide_identity",
        "divide_zero",
        "divide_self",
        "power_zero",
        "power_one",
        "zero_power",
        "one_power",
        "constant_fold",
    }
)

# Mapping from concept network concept names to rule names.
# If a concept with one of these names exists in the concept network
# (with confidence >= 0.3), the corresponding rule is enabled.
_CONCEPT_TO_RULE: dict[str, str] = {
    "additive identity": "additive_identity",
    "additive inverse": "additive_inverse",
    "subtract zero": "subtract_zero",
    "subtract self": "subtract_self",
    "multiplicative zero": "multiplicative_zero",
    "multiplicative identity": "multiplicative_identity",
    "multiplicative inverse": "multiplicative_inverse",
    "divide identity": "divide_identity",
    "divide zero": "divide_zero",
    "divide self": "divide_self",
    "power zero": "power_zero",
    "power one": "power_one",
    "zero power": "zero_power",
    "one power": "one_power",
    "constant folding": "constant_fold",
    # Higher-level concepts that imply multiple rules
    "commutative property": "constant_fold",  # commutativity enables reordering
    "algebraic identity": "constant_fold",
}

# Rules that are always enabled regardless of the concept network,
# because they're fundamental to the parser/evaluator working at all.
_BASE_RULES: frozenset[str] = frozenset({"constant_fold"})


class MathRuleRegistry:
    """Registry of math rules enabled based on the concept network.

    This bridges the concept network (Genesis's learned knowledge) and
    the math engine (the computational substrate). Rules are enabled
    when Genesis has learned the corresponding concept.

    Usage:
        registry = MathRuleRegistry.from_concept_network(network)
        result = simplify(expr, registry.enabled_rules)
    """

    def __init__(self, enabled_rules: set[str] | None = None) -> None:
        """Initialize the registry, enabling all rules by default or a custom subset."""
        self.enabled_rules: set[str] = set(enabled_rules) if enabled_rules else set(_ALL_RULES)

    def has_rule(self, name: str) -> bool:
        """Return True if *name* is in the enabled rule set."""
        return name in self.enabled_rules

    @classmethod
    def from_concept_network(cls, network: Any) -> MathRuleRegistry:
        """Build a rule registry from concepts in the network.

        A rule is enabled if:
        1. It's a base rule (always enabled), OR
        2. A concept with the corresponding name exists in the network
           with confidence >= 0.3

        If no math concepts are found in the network at all, all rules
        are enabled (backward compatible — the engine assumes a
        pre-trained network or standalone usage).
        """
        enabled: set[str] = set(_BASE_RULES)
        found_any_math = False

        for concept_name, rule_name in _CONCEPT_TO_RULE.items():
            concept = network.get_concept(concept_name)
            if concept is not None and concept.confidence >= 0.3:
                enabled.add(rule_name)
                found_any_math = True

        # If no math concepts were found, enable all rules (backward compat)
        if not found_any_math:
            return cls()  # all rules

        return cls(enabled)


def simplify(node: Any, enabled_rules: set[str] | None = None) -> Any:
    """Simplify an expression tree by applying algebraic identities.

    Parameters:
        node: The AST node to simplify.
        enabled_rules: Optional set of rule names to apply. If None,
            all rules are enabled (backward compatible). If provided,
            only rules whose names are in the set are applied.

    Rule names:
        - "additive_identity": a + 0 = a, 0 + a = a
        - "additive_inverse": a + (-a) = 0, (-a) + a = 0
        - "subtract_zero": a - 0 = a
        - "subtract_self": a - a = 0
        - "multiplicative_zero": a * 0 = 0, 0 * a = 0
        - "multiplicative_identity": a * 1 = a, 1 * a = a
        - "multiplicative_inverse": a * (-1) = -a, (-1) * a = -a
        - "divide_identity": a / 1 = a
        - "divide_zero": 0 / a = 0
        - "divide_self": a / a = 1
        - "power_zero": a ^ 0 = 1
        - "power_one": a ^ 1 = a
        - "zero_power": 0 ^ a = 0 (a > 0)
        - "one_power": 1 ^ a = 1
        - "constant_fold": evaluate numeric subexpressions

    This makes the simplifier's rule set configurable. The
    ``MathRuleRegistry.from_concept_network`` method builds the
    enabled_rules set from concepts in the concept network, so
    that rules Genesis has learned are applied and rules it
    hasn't learned are skipped.
    """
    if enabled_rules is None:
        enabled_rules = set(_ALL_RULES)

    if isinstance(node, (Num, Var)):
        return node

    if isinstance(node, UnaryOp):
        operand = simplify(node.operand, enabled_rules)
        if isinstance(operand, Num):
            if node.op == "-":
                return Num(-operand.value)
            return operand
        return UnaryOp(node.op, operand)

    if isinstance(node, FuncCall):
        args = [simplify(a, enabled_rules) for a in node.args]
        # If all args are numeric, evaluate
        if "constant_fold" in enabled_rules and all(isinstance(a, Num) for a in args):
            try:
                result = evaluate(FuncCall(node.name, args))
                return Num(result)
            except EvalError as e:
                logger.debug(repr(e))
        return FuncCall(node.name, args)

    if isinstance(node, BinOp):
        left = simplify(node.left, enabled_rules)
        right = simplify(node.right, enabled_rules)

        # If both sides are numeric, evaluate
        if "constant_fold" in enabled_rules and isinstance(left, Num) and isinstance(right, Num):
            try:
                result = evaluate(BinOp(node.op, left, right))
                return Num(result)
            except EvalError as e:
                logger.debug(repr(e))

        # Algebraic identities — each guarded by its rule name
        simplified = _apply_binop_identities(node.op, left, right, enabled_rules)
        if simplified is not None:
            return simplified
        return BinOp(node.op, left, right)

    return node


def _apply_binop_identities(
    op: str, left: Any, right: Any, enabled_rules: set[str]
) -> Any | None:
    """Apply algebraic identity rules to a binary operation.

    Returns the simplified node if an identity matched, or None to
    signal that no identity applied (caller should rebuild the BinOp).
    Each identity is guarded by its rule name in ``enabled_rules``.
    """
    handlers = {
        "+": _identity_add,
        "-": _identity_sub,
        "*": _identity_mul,
        "/": _identity_div,
        "^": _identity_pow,
    }
    handler = handlers.get(op)
    if handler is None:
        return None
    return handler(left, right, enabled_rules)


def _identity_add(left: Any, right: Any, enabled_rules: set[str]) -> Any | None:
    """Algebraic identities for addition: a+0, 0+a, a+(-a), (-a)+a."""
    if "additive_identity" in enabled_rules:
        # a + 0 = a
        if isinstance(right, Num) and right.value == 0:
            return left
        # 0 + a = a
        if isinstance(left, Num) and left.value == 0:
            return right
    if "additive_inverse" in enabled_rules:
        # a + (-a) = 0
        if isinstance(right, UnaryOp) and right.op == "-":
            if _expr_equal(left, right.operand):
                return Num(0)
        # (-a) + a = 0
        if isinstance(left, UnaryOp) and left.op == "-":
            if _expr_equal(left.operand, right):
                return Num(0)
    return None


def _identity_sub(left: Any, right: Any, enabled_rules: set[str]) -> Any | None:
    """Algebraic identities for subtraction: a-0, a-a, 0-a."""
    if "subtract_zero" in enabled_rules:
        # a - 0 = a
        if isinstance(right, Num) and right.value == 0:
            return left
    if "subtract_self" in enabled_rules:
        # a - a = 0
        if _expr_equal(left, right):
            return Num(0)
    # 0 - a = -a (part of additive identity)
    if "additive_identity" in enabled_rules:
        if isinstance(left, Num) and left.value == 0:
            return UnaryOp("-", right)
    return None


def _identity_mul(left: Any, right: Any, enabled_rules: set[str]) -> Any | None:
    """Algebraic identities for multiplication: a*0, a*1, a*(-1)."""
    if "multiplicative_zero" in enabled_rules:
        # a * 0 = 0
        if isinstance(right, Num) and right.value == 0:
            return Num(0)
        if isinstance(left, Num) and left.value == 0:
            return Num(0)
    if "multiplicative_identity" in enabled_rules:
        # a * 1 = a
        if isinstance(right, Num) and right.value == 1:
            return left
        # 1 * a = a
        if isinstance(left, Num) and left.value == 1:
            return right
    if "multiplicative_inverse" in enabled_rules:
        # a * (-1) = -a
        if isinstance(right, Num) and right.value == -1:
            return UnaryOp("-", left)
        if isinstance(left, Num) and left.value == -1:
            return UnaryOp("-", right)
    return None


def _identity_div(left: Any, right: Any, enabled_rules: set[str]) -> Any | None:
    """Algebraic identities for division: a/1, 0/a, a/a."""
    if "divide_identity" in enabled_rules:
        # a / 1 = a
        if isinstance(right, Num) and right.value == 1:
            return left
    if "divide_zero" in enabled_rules:
        # 0 / a = 0 (a ≠ 0)
        if isinstance(left, Num) and left.value == 0:
            if not (isinstance(right, Num) and right.value == 0):
                return Num(0)
    if "divide_self" in enabled_rules:
        # a / a = 1 (a ≠ 0)
        if _expr_equal(left, right):
            # Don't simplify 0/0 — it's undefined
            if isinstance(left, Num) and left.value == 0:
                return None
            return Num(1)
    return None


def _identity_pow(left: Any, right: Any, enabled_rules: set[str]) -> Any | None:
    """Algebraic identities for exponentiation: a^0, a^1, 0^a, 1^a."""
    if "power_zero" in enabled_rules:
        # a ^ 0 = 1
        if isinstance(right, Num) and right.value == 0:
            return Num(1)
    if "power_one" in enabled_rules:
        # a ^ 1 = a
        if isinstance(right, Num) and right.value == 1:
            return left
    if "zero_power" in enabled_rules:
        # 0 ^ a = 0 (a > 0)
        if isinstance(left, Num) and left.value == 0:
            if isinstance(right, Num) and right.value > 0:
                return Num(0)
    if "one_power" in enabled_rules:
        # 1 ^ a = 1
        if isinstance(left, Num) and left.value == 1:
            return Num(1)
    return None


def _expr_equal(a: Any, b: Any) -> bool:
    """Check if two expression trees are structurally equal."""
    if type(a) is not type(b):
        return False
    if isinstance(a, Num):
        return a.value == b.value
    if isinstance(a, Var):
        return a.name == b.name
    if isinstance(a, BinOp):
        return a.op == b.op and _expr_equal(a.left, b.left) and _expr_equal(a.right, b.right)
    if isinstance(a, UnaryOp):
        return a.op == b.op and _expr_equal(a.operand, b.operand)
    if isinstance(a, FuncCall):
        return (
            a.name == b.name
            and len(a.args) == len(b.args)
            and all(_expr_equal(x, y) for x, y in zip(a.args, b.args, strict=True))
        )
    return False


def _term_key(node: Any) -> str:
    """Generate a canonical string key for a term, ignoring order.

    For example, a*b and b*a both produce the same key.
    """
    if isinstance(node, Num):
        return f"num:{node.value}"
    if isinstance(node, Var):
        return f"var:{node.name}"
    if isinstance(node, BinOp):
        if node.op == "*":
            # Multiplication is commutative — sort factors
            factors = _flatten_factors(node)
            return "mul:" + ",".join(sorted(factors))
        if node.op == "+":
            return "add:" + _term_key(node.left) + "," + _term_key(node.right)
        return f"binop:{node.op}:{_term_key(node.left)},{_term_key(node.right)}"
    if isinstance(node, UnaryOp):
        return f"unary:{node.op}:{_term_key(node.operand)}"
    if isinstance(node, FuncCall):
        return f"func:{node.name}:{','.join(_term_key(a) for a in node.args)}"
    return str(node)


def _flatten_factors(node: Any) -> list[str]:
    """Flatten a multiplication tree into a list of factor keys."""
    if isinstance(node, BinOp) and node.op == "*":
        return _flatten_factors(node.left) + _flatten_factors(node.right)
    return [_term_key(node)]


def _collect_terms(node: Any) -> Any:
    """Collect like terms in a sum.

    Converts a*a + a*b + b*a + b*b into a*a + 2*a*b + b*b by
    combining terms with the same factors (using commutativity).
    """
    if not isinstance(node, BinOp):
        return node

    # Recursively collect sub-expressions first
    left = _collect_terms(node.left)
    right = _collect_terms(node.right)
    node = BinOp(node.op, left, right)

    if node.op != "+":
        return node

    # Flatten the sum into a list of terms
    terms = _flatten_sum(node)

    # Group terms by their factor signature (ignoring numeric coefficient)
    grouped: dict[str, list[Any]] = {}
    coefficients: dict[str, float] = {}
    term_order: list[str] = []

    for term in terms:
        coeff, factors = _extract_coeff_and_factors(term)
        key = ",".join(sorted(factors))
        if key not in grouped:
            grouped[key] = []
            coefficients[key] = 0.0
            term_order.append(key)
        grouped[key].append(term)
        coefficients[key] += coeff

    # Rebuild the sum with collected coefficients
    result_terms: list[Any] = []
    for key in term_order:
        coeff = coefficients[key]
        if coeff == 0:
            continue
        # Get the factor part from the first term in the group
        _, factors = _extract_coeff_and_factors(grouped[key][0])
        if not factors:
            # Pure constant term
            result_terms.append(Num(coeff))
        elif coeff == 1:
            # Just the factors, no coefficient
            result_terms.append(_build_product(factors))
        else:
            # Coefficient * factors
            result_terms.append(BinOp("*", Num(coeff), _build_product(factors)))

    if not result_terms:
        return Num(0)
    if len(result_terms) == 1:
        return result_terms[0]

    # Build the sum
    result = result_terms[0]
    for term in result_terms[1:]:
        result = BinOp("+", result, term)
    return result


def _flatten_sum(node: Any) -> list[Any]:
    """Flatten an addition tree into a list of terms."""
    if isinstance(node, BinOp) and node.op == "+":
        return _flatten_sum(node.left) + _flatten_sum(node.right)
    return [node]


def _extract_coeff_and_factors(node: Any) -> tuple[float, list[str]]:
    """Extract the numeric coefficient and factor keys from a term.

    For example, 3*a*b → (3.0, ["var:a", "var:b"])
    a*b → (1.0, ["var:a", "var:b"])
    5 → (5.0, [])
    """
    if isinstance(node, Num):
        return (float(node.value), [])
    if isinstance(node, Var):
        return (1.0, [_term_key(node)])
    if isinstance(node, BinOp) and node.op == "*":
        left_coeff, left_factors = _extract_coeff_and_factors(node.left)
        right_coeff, right_factors = _extract_coeff_and_factors(node.right)
        return (left_coeff * right_coeff, left_factors + right_factors)
    if isinstance(node, BinOp) and node.op == "^":
        # var^n → factor is "var^n"
        return (1.0, [_term_key(node)])
    if isinstance(node, UnaryOp) and node.op == "-":
        coeff, factors = _extract_coeff_and_factors(node.operand)
        return (-coeff, factors)
    return (1.0, [_term_key(node)])


def _build_product(factors: list[str]) -> Any:
    """Build a product expression from a list of factor keys."""
    if not factors:
        return Num(1)
    # Convert factor keys back to simple expressions
    # This is simplified — just use Var for var: keys
    nodes: list[Any] = []
    for f in factors:
        if f.startswith("var:"):
            nodes.append(Var(f[4:]))
        elif f.startswith("num:"):
            val = f[4:]
            try:
                nodes.append(Num(float(val)))
            except ValueError:
                nodes.append(Var(f))
        else:
            # Complex factor — use as-is via a placeholder
            nodes.append(Var(f))
    if len(nodes) == 1:
        return nodes[0]
    result = nodes[0]
    for n in nodes[1:]:
        result = BinOp("*", result, n)
    return result


def _expr_to_str(node: Any) -> str:
    """Convert an expression tree to a readable string."""
    if isinstance(node, Num):
        return format_number(node.value)
    if isinstance(node, Var):
        return node.name
    if isinstance(node, BinOp):
        left = _expr_to_str(node.left)
        right = _expr_to_str(node.right)
        # Add parens for clarity when needed
        if isinstance(node.left, BinOp) and _PRECEDENCE_OF.get(
            node.left.op, 0
        ) < _PRECEDENCE_OF.get(node.op, 0):
            left = f"({left})"
        if isinstance(node.right, BinOp) and _PRECEDENCE_OF.get(
            node.right.op, 0
        ) < _PRECEDENCE_OF.get(node.op, 0):
            right = f"({right})"
        return f"{left} {node.op} {right}"
    if isinstance(node, UnaryOp):
        return f"-{_expr_to_str(node.operand)}"
    if isinstance(node, FuncCall):
        return f"{node.name}({_expr_to_str(node.args[0]) if node.args else ''})"
    return str(node)


_PRECEDENCE_OF = {"+": 2, "-": 2, "*": 3, "/": 3, "^": 4}


@dataclass
class SolveStep:
    """A single step in a solution."""

    description: str
    expression: str


@dataclass
class SolveResult:
    """Result of solving an equation."""

    solution: str
    steps: list[SolveStep] = field(default_factory=list)
    variable: str = ""
    success: bool = True


def _solve_early_return(
    all_vars: set[str], eq: Equation, steps: list[SolveStep]
) -> SolveResult | None:
    """Handle the no-variable and multi-variable cases before solving.

    Returns a SolveResult for the trivial cases (no variables → evaluate
    both sides; multiple variables → cannot solve), or None to let the
    caller proceed with single-variable solving.
    """
    if len(all_vars) == 0:
        # No variables — just evaluate both sides
        try:
            left_val = evaluate(eq.left)
            right_val = evaluate(eq.right)
            if abs(left_val - right_val) < 1e-10:
                return SolveResult("True", steps, "", True)
            return SolveResult("False", steps, "", True)
        except EvalError:
            return SolveResult("Cannot evaluate", steps, "", False)
    if len(all_vars) > 1:
        return SolveResult(
            f"Cannot solve — multiple variables: {', '.join(sorted(all_vars))}",
            steps,
            "",
            False,
        )
    return None


def solve_equation(eq: Equation, enabled_rules: set[str] | None = None) -> SolveResult:
    """Solve a linear or quadratic equation for its variable.

    Uses transformation rules (balance, isolate, simplify) applied
    mechanically by the engine. The simplification rules are gated by
    ``enabled_rules`` (see ``simplify()`` for the rule names). The
    steps are recorded so Genesis can explain its reasoning.
    """
    steps: list[SolveStep] = []

    # Find the variable to solve for
    all_vars = collect_variables(eq.left) | collect_variables(eq.right)
    early = _solve_early_return(all_vars, eq, steps)
    if early is not None:
        return early

    var_name = all_vars.pop()
    steps.append(
        SolveStep(
            f"Solve for {var_name}",
            _expr_to_str(eq.left) + f" {eq.comparator} " + _expr_to_str(eq.right),
        )
    )

    # Move everything to the left side: left - right = 0
    left = simplify(BinOp("-", eq.left, eq.right), enabled_rules)
    steps.append(
        SolveStep(
            "Move all terms to one side",
            f"{_expr_to_str(left)} = 0",
        )
    )

    # Expand and collect terms
    expanded = _expand(left)
    expanded = simplify(expanded, enabled_rules)
    expanded = _normalize_powers(expanded)
    steps.append(
        SolveStep(
            "Simplify",
            f"{_expr_to_str(expanded)} = 0",
        )
    )

    # Classify: linear (a*x + b) or quadratic (a*x^2 + b*x + c)
    coeffs = _extract_coefficients(expanded, var_name)

    if coeffs is None:
        return SolveResult(
            f"Cannot solve — expression too complex: {_expr_to_str(expanded)} = 0",
            steps,
            var_name,
            False,
        )

    degree = max(k for k in coeffs if k > 0) if any(k > 0 for k in coeffs) else 0

    if degree == 1:
        return _solve_linear(coeffs, var_name, steps)

    if degree == 2:
        return _solve_quadratic(coeffs, var_name, steps)

    return SolveResult(
        f"Cannot solve — degree {degree} equations not supported",
        steps,
        var_name,
        False,
    )


def _solve_linear(
    coeffs: dict[int, float], var_name: str, steps: list[SolveStep]
) -> SolveResult:
    """Solve a linear equation a*x + b = 0 → x = -b/a."""
    # Linear: a*x + b = 0 → x = -b/a
    a = coeffs.get(1, 0)
    b = coeffs.get(0, 0)
    if a == 0:
        if b == 0:
            return SolveResult("Infinite solutions (identity)", steps, var_name, True)
        return SolveResult("No solution (contradiction)", steps, var_name, True)
    solution = -b / a
    steps.append(
        SolveStep(
            f"Divide both sides by {format_number(a)}",
            f"{var_name} = {format_number(-b)} / {format_number(a)}",
        )
    )
    result = format_number(solution)
    steps.append(
        SolveStep(
            "Compute the result",
            f"{var_name} = {result}",
        )
    )
    return SolveResult(f"{var_name} = {result}", steps, var_name, True)


def _solve_quadratic(
    coeffs: dict[int, float], var_name: str, steps: list[SolveStep]
) -> SolveResult:
    """Solve a quadratic a*x^2 + b*x + c = 0 via the quadratic formula."""
    # Quadratic: a*x^2 + b*x + c = 0 → quadratic formula
    a = coeffs.get(2, 0)
    b = coeffs.get(1, 0)
    c = coeffs.get(0, 0)
    if a == 0:
        # Degenerate — treat as linear
        if b == 0:
            if c == 0:
                return SolveResult("Infinite solutions", steps, var_name, True)
            return SolveResult("No solution", steps, var_name, True)
        solution = -c / b
        return SolveResult(f"{var_name} = {format_number(solution)}", steps, var_name, True)

    discriminant = b * b - 4 * a * c
    steps.append(
        SolveStep(
            "Apply the quadratic formula",
            f"{var_name} = ({-b} ± sqrt({b}^2 - 4*{a}*{c})) / (2*{a})",
        )
    )
    steps.append(
        SolveStep(
            "Compute the discriminant",
            f"discriminant = {format_number(discriminant)}",
        )
    )

    if discriminant > 0:
        sqrt_d = math.sqrt(discriminant)
        x1 = (-b + sqrt_d) / (2 * a)
        x2 = (-b - sqrt_d) / (2 * a)
        result = f"{var_name} = {format_number(x1)} or {var_name} = {format_number(x2)}"
        steps.append(
            SolveStep(
                "Two real solutions",
                result,
            )
        )
        return SolveResult(result, steps, var_name, True)
    elif discriminant == 0:
        x = -b / (2 * a)
        result = f"{var_name} = {format_number(x)}"
        steps.append(
            SolveStep(
                "One real solution (repeated root)",
                result,
            )
        )
        return SolveResult(result, steps, var_name, True)
    else:
        real_part = -b / (2 * a)
        imag_part = math.sqrt(-discriminant) / (2 * a)
        result = (
            f"{var_name} = {format_number(real_part)} + {format_number(imag_part)}i "
            f"or {var_name} = {format_number(real_part)} - {format_number(imag_part)}i"
        )
        steps.append(
            SolveStep(
                "Two complex solutions",
                result,
            )
        )
        return SolveResult(result, steps, var_name, True)


def _expand(node: Any) -> Any:
    """Expand an expression by distributing multiplication over addition
    and expanding small integer exponents."""
    if isinstance(node, BinOp):
        left = _expand(node.left)
        right = _expand(node.right)

        if node.op == "*":
            # (a + b) * c → a*c + b*c
            if isinstance(left, BinOp) and left.op in ("+", "-"):
                return BinOp(
                    left.op,
                    _expand(BinOp("*", left.left, right)),
                    _expand(BinOp("*", left.right, right)),
                )
            # a * (b + c) → a*b + a*c
            if isinstance(right, BinOp) and right.op in ("+", "-"):
                return BinOp(
                    right.op,
                    _expand(BinOp("*", left, right.left)),
                    _expand(BinOp("*", left, right.right)),
                )

        if node.op == "^":
            # Expand (a + b)^n for small integer n by repeated multiplication
            if isinstance(right, Num) and isinstance(right.value, int) and 2 <= right.value <= 4:
                n = right.value
                # Build the product by repeated multiplication
                result = left
                for _ in range(n - 1):
                    result = BinOp("*", result, _expand(left))
                return _expand(result)
            # Also handle float exponents that are integers
            if (
                isinstance(right, Num)
                and isinstance(right.value, float)
                and right.value.is_integer()
                and 2 <= right.value <= 4
            ):
                n = int(right.value)
                result = left
                for _ in range(n - 1):
                    result = BinOp("*", result, _expand(left))
                return _expand(result)

        return BinOp(node.op, left, right)

    if isinstance(node, UnaryOp):
        return UnaryOp(node.op, _expand(node.operand))

    if isinstance(node, FuncCall):
        return FuncCall(node.name, [_expand(a) for a in node.args])

    return node


def _normalize_powers(node: Any) -> Any:
    """Convert repeated multiplication of the same variable into powers.

    For example, x * x → x^2, x * x * x → x^3.
    """
    if isinstance(node, BinOp):
        left = _normalize_powers(node.left)
        right = _normalize_powers(node.right)

        if node.op == "*":
            # Collect all factors
            factors = _flatten_mul(left) + _flatten_mul(right)
            # Group by variable name
            var_counts: dict[str, int] = {}
            other_factors: list[Any] = []
            for f in factors:
                if isinstance(f, Var):
                    var_counts[f.name] = var_counts.get(f.name, 0) + 1
                else:
                    other_factors.append(f)
            # Rebuild with powers
            result_factors: list[Any] = []
            for var_name, count in var_counts.items():
                if count == 1:
                    result_factors.append(Var(var_name))
                else:
                    result_factors.append(BinOp("^", Var(var_name), Num(count)))
            result_factors.extend(other_factors)

            if not result_factors:
                return Num(1)
            if len(result_factors) == 1:
                return result_factors[0]
            result = result_factors[0]
            for f in result_factors[1:]:
                result = BinOp("*", result, f)
            return result

        return BinOp(node.op, left, right)

    if isinstance(node, UnaryOp):
        return UnaryOp(node.op, _normalize_powers(node.operand))

    if isinstance(node, FuncCall):
        return FuncCall(node.name, [_normalize_powers(a) for a in node.args])

    return node


def _flatten_mul(node: Any) -> list[Any]:
    """Flatten a multiplication tree into a list of factors."""
    if isinstance(node, BinOp) and node.op == "*":
        return _flatten_mul(node.left) + _flatten_mul(node.right)
    return [node]


def _extract_coefficients(node: Any, var: str) -> dict[int, float] | None:
    """Extract polynomial coefficients from an expression.

    Returns a dict {degree: coefficient} or None if the expression
    is not a polynomial in the given variable.
    """
    coeffs: dict[int, float] = {}

    def add_term(degree: int, coeff: float) -> None:
        """Accumulate *coeff* into the *degree* coefficient."""
        coeffs[degree] = coeffs.get(degree, 0) + coeff

    def extract(n: Any, sign: float = 1.0) -> bool:
        """Recursively extract polynomial terms from node *n*."""
        if isinstance(n, Num):
            add_term(0, sign * n.value)
            return True
        if isinstance(n, Var):
            if n.name == var:
                add_term(1, sign)
                return True
            # Other variables — can't handle
            return False
        if isinstance(n, UnaryOp) and n.op == "-":
            return extract(n.operand, -sign)
        if isinstance(n, BinOp):
            if n.op == "+":
                return extract(n.left, sign) and extract(n.right, sign)
            if n.op == "-":
                return extract(n.left, sign) and extract(n.right, -sign)
            if n.op == "*":
                return _extract_multiplication(n, var, sign, add_term)
            if n.op == "^":
                return _extract_power(n, var, sign, add_term)
            if n.op == "/":
                return _extract_division(n, var, sign, add_term)
        return False

    if extract(node):
        return coeffs
    return None


def _extract_multiplication(
    n: Any, var: str, sign: float, add_term
) -> bool:
    """Extract coefficients from a multiplication BinOp (constant × polynomial).

    One side must be a constant, the other a polynomial term in ``var``.
    Returns True if successfully extracted, False otherwise.
    """
    # One side must be a constant, the other a polynomial term
    left_coeffs = _try_constant(n.left)
    right_coeffs = _try_constant(n.right)
    if left_coeffs is not None:
        # constant * polynomial
        sub = _extract_coefficients(n.right, var)
        if sub is None:
            return False
        for deg, coef in sub.items():
            add_term(deg, sign * left_coeffs * coef)
        return True
    if right_coeffs is not None:
        sub = _extract_coefficients(n.left, var)
        if sub is None:
            return False
        for deg, coef in sub.items():
            add_term(deg, sign * right_coeffs * coef)
        return True
    return False


def _extract_power(n: Any, var: str, sign: float, add_term) -> bool:
    """Extract coefficients from an exponentiation BinOp (var^int or const^int).

    Handles ``var ^ integer`` (adds a term of that degree) and
    ``constant ^ integer`` (evaluates and adds a degree-0 term).
    Returns True if successfully extracted, False otherwise.
    """
    # var ^ integer
    if isinstance(n.left, Var) and n.left.name == var and isinstance(n.right, Num):
        exp = n.right.value
        if isinstance(exp, int) or (isinstance(exp, float) and exp.is_integer()):
            add_term(int(exp), sign)
            return True
    # constant ^ integer
    if isinstance(n.left, Num) and isinstance(n.right, Num):
        try:
            val = evaluate(n)
            add_term(0, sign * val)
            return True
        except EvalError:
            return False
    return False


def _extract_division(n: Any, var: str, sign: float, add_term) -> bool:
    """Extract coefficients from a division BinOp (polynomial ÷ constant).

    The divisor must be a non-zero constant. Returns True if
    successfully extracted, False otherwise.
    """
    # polynomial / constant
    divisor = _try_constant(n.right)
    if divisor is not None and divisor != 0:
        sub = _extract_coefficients(n.left, var)
        if sub is None:
            return False
        for deg, coef in sub.items():
            add_term(deg, sign * coef / divisor)
        return True
    return False


def _try_constant(node: Any) -> float | None:
    """Try to evaluate a node as a constant (no variables)."""
    if not collect_variables(node):
        try:
            return evaluate(node)
        except EvalError:
            return None
    return None


# ═══════════════════════════════════════════════════════════════════════
# Part 4: Proof Engine
# ═══════════════════════════════════════════════════════════════════════


@dataclass
class ProofStep:
    """A single step in a proof."""

    statement: str
    justification: str


@dataclass
class ProofResult:
    """Result of a proof attempt."""

    conclusion: str
    steps: list[ProofStep] = field(default_factory=list)
    success: bool = True
    proof_type: str = ""


def prove(statement: str) -> ProofResult:
    """Attempt to prove a mathematical statement.

    The proof strategies are a mix of genuine computation and
    hardcoded templates:
    - Arithmetic identities: verified by computation (genuine)
    - Even/odd properties: hardcoded proof templates (not generated)
    - Algebraic identities: verified by expansion (genuine)
    - Induction for sum formulas: hardcoded template (not generated)
    """
    statement = statement.strip().rstrip(".")
    lower = statement.lower()

    # ── Strategy 1: Arithmetic identity (verify by computation) ──
    result = _prove_arithmetic_identity(statement, lower)
    if result is not None:
        return result

    # ── Strategy 2: Even/odd properties ──
    result = _prove_even_odd(lower)
    if result is not None:
        return result

    # ── Strategy 3: Proof by induction (sum formulas) ──
    result = _prove_induction(lower)
    if result is not None:
        return result

    # ── Strategy 4: Algebraic identity (verify by expansion) ──
    result = _prove_algebraic_expansion(statement, lower)
    if result is not None:
        return result

    return ProofResult(
        "cannot prove this statement yet — no strategy for it",
        [],
        False,
        "",
    )


def _strip_proof_prefix(statement: str, lower: str) -> str:
    """Strip a leading 'prove that'/'show' prefix from the statement."""
    eq_part = statement
    for prefix in ("prove that ", "prove ", "show that ", "show "):
        if lower.startswith(prefix):
            eq_part = statement[len(prefix) :]
            break
    return eq_part


def _prove_arithmetic_identity(statement: str, lower: str) -> ProofResult | None:
    """Strategy 1: verify an arithmetic identity by computing both sides."""
    # "Prove that 2 + 3 = 5" → compute both sides
    if "=" not in statement or ("prove" not in lower and "show" not in lower):
        return None
    eq_part = _strip_proof_prefix(statement, lower)
    try:
        parsed = parse_expression(eq_part)
        if isinstance(parsed, Equation):
            left_val = evaluate(parsed.left)
            right_val = evaluate(parsed.right)
            steps = [
                ProofStep(
                    f"We need to show that {_expr_to_str(parsed.left)} = "
                    f"{_expr_to_str(parsed.right)}",
                    "Given",
                ),
                ProofStep(
                    f"Evaluate the left side: {_expr_to_str(parsed.left)} = "
                    f"{format_number(left_val)}",
                    "Computation",
                ),
                ProofStep(
                    f"Evaluate the right side: {_expr_to_str(parsed.right)} = "
                    f"{format_number(right_val)}",
                    "Computation",
                ),
            ]
            if abs(left_val - right_val) < 1e-10:
                steps.append(
                    ProofStep(
                        f"Both sides equal {format_number(left_val)}, so the identity holds",
                        "QED",
                    )
                )
                return ProofResult(
                    f"Proven: {_expr_to_str(parsed.left)} = {_expr_to_str(parsed.right)}",
                    steps,
                    True,
                    "direct computation",
                )
            else:
                steps.append(
                    ProofStep(
                        f"Left side = {format_number(left_val)} ≠ right side = "
                        f"{format_number(right_val)}",
                        "Contradiction",
                    )
                )
                return ProofResult(
                    "Disproven: the statement is false",
                    steps,
                    False,
                    "direct computation",
                )
    except (ParseError, EvalError) as e:
        logger.debug(repr(e))
    return None


def _prove_even_odd(lower: str) -> ProofResult | None:
    """Strategy 2: hardcoded even/odd proof templates."""
    # "Prove that the sum of two even numbers is even"
    # Check "odd" patterns first since "even" appears in both
    if "odd" in lower and ("sum" in lower or "plus" in lower or "+" in lower):
        return _proof_odd_sum()
    if "even" in lower and ("sum" in lower or "plus" in lower or "+" in lower):
        return _proof_even_sum()
    if "even" in lower and ("product" in lower or "times" in lower or "*" in lower):
        return _proof_even_product()
    return None


def _proof_odd_sum() -> ProofResult:
    """Template: the sum of two odd numbers is even."""
    steps = [
        ProofStep("Let a and b be odd numbers", "Assumption"),
        ProofStep(
            "By definition, a = 2k + 1 for some integer k, and b = 2m + 1 for some integer m",
            "Definition of odd number",
        ),
        ProofStep(
            "a + b = (2k + 1) + (2m + 1) = 2k + 2m + 2 = 2(k + m + 1)",
            "Substitution and simplification",
        ),
        ProofStep(
            "Since k + m + 1 is an integer, 2(k + m + 1) is even by definition",
            "Definition of even number",
        ),
        ProofStep(
            "Therefore, the sum of two odd numbers is even",
            "QED",
        ),
    ]
    return ProofResult(
        "The sum of two odd numbers is even",
        steps,
        True,
        "direct proof",
    )


def _proof_even_sum() -> ProofResult:
    """Template: the sum of two even numbers is even."""
    steps = [
        ProofStep(
            "Let a and b be even numbers",
            "Assumption",
        ),
        ProofStep(
            "By definition, a = 2k for some integer k, and b = 2m for some integer m",
            "Definition of even number",
        ),
        ProofStep(
            "a + b = 2k + 2m = 2(k + m)",
            "Substitution and factoring",
        ),
        ProofStep(
            "Since k + m is an integer, 2(k + m) is even by definition",
            "Definition of even number",
        ),
        ProofStep(
            "Therefore, the sum of two even numbers is even",
            "QED",
        ),
    ]
    return ProofResult(
        "The sum of two even numbers is even",
        steps,
        True,
        "direct proof",
    )


def _proof_even_product() -> ProofResult:
    """Template: the product of two even numbers is even."""
    steps = [
        ProofStep("Let a and b be even numbers", "Assumption"),
        ProofStep(
            "By definition, a = 2k for some integer k, and b = 2m for some integer m",
            "Definition of even number",
        ),
        ProofStep(
            "a × b = 2k × 2m = 4km = 2(2km)",
            "Substitution and factoring",
        ),
        ProofStep(
            "Since 2km is an integer, 2(2km) is even by definition",
            "Definition of even number",
        ),
        ProofStep(
            "Therefore, the product of two even numbers is even",
            "QED",
        ),
    ]
    return ProofResult(
        "The product of two even numbers is even",
        steps,
        True,
        "direct proof",
    )


def _prove_induction(lower: str) -> ProofResult | None:
    """Strategy 3: hardcoded induction template for sum formulas."""
    # "Prove that 1 + 2 + ... + n = n(n+1)/2"
    induction_match = re.match(
        r"prove.*?(\d+)\s*\+\s*(\d+)\s*\+\s*\.\.\.\s*\+\s*n\s*=\s*(.+)",
        lower,
    )
    if induction_match:
        first, second = int(induction_match.group(1)), int(induction_match.group(2))
        if first == 1 and second == 2:
            # Sum of 1 to n = n(n+1)/2
            steps = [
                ProofStep(
                    "We prove by mathematical induction that 1 + 2 + ... + n = n(n+1)/2",
                    "Proof strategy: mathematical induction",
                ),
                ProofStep(
                    "Base case (n = 1): Left side = 1, right side = 1(1+1)/2 = 1. ✓",
                    "Base case verified by computation",
                ),
                ProofStep(
                    "Inductive hypothesis: Assume 1 + 2 + ... + k = k(k+1)/2 for some k ≥ 1",
                    "Inductive hypothesis",
                ),
                ProofStep(
                    "Inductive step: 1 + 2 + ... + k + (k+1) = k(k+1)/2 + (k+1)",
                    "Apply inductive hypothesis",
                ),
                ProofStep(
                    "= (k+1)(k/2 + 1) = (k+1)(k+2)/2",
                    "Factor out (k+1) and simplify",
                ),
                ProofStep(
                    "This is exactly the formula with n = k+1, so the statement holds for k+1",
                    "Inductive step complete",
                ),
                ProofStep(
                    "By the principle of mathematical induction, the formula holds for all n ≥ 1",
                    "QED",
                ),
            ]
            return ProofResult(
                "1 + 2 + ... + n = n(n+1)/2 for all natural numbers n",
                steps,
                True,
                "mathematical induction",
            )
    return None


def _prove_algebraic_expansion(statement: str, lower: str) -> ProofResult | None:
    """Strategy 4: verify an algebraic identity by expanding both sides."""
    # "Prove that (a+b)^2 = a^2 + 2ab + b^2"
    if "=" not in statement or ("prove" not in lower and "show" not in lower):
        return None
    eq_part = _strip_proof_prefix(statement, lower)
    try:
        parsed = parse_expression(eq_part)
        if isinstance(parsed, Equation):
            # Try expanding and collecting terms on both sides
            left_expanded = _collect_terms(simplify(_expand(parsed.left)))
            right_expanded = _collect_terms(simplify(_expand(parsed.right)))
            if _expr_equal(left_expanded, right_expanded):
                steps = [
                    ProofStep(
                        f"We need to show that {_expr_to_str(parsed.left)} = "
                        f"{_expr_to_str(parsed.right)}",
                        "Given",
                    ),
                    ProofStep(
                        f"Expand the left side: {_expr_to_str(parsed.left)} = "
                        f"{_expr_to_str(left_expanded)}",
                        "Algebraic expansion",
                    ),
                    ProofStep(
                        f"Expand the right side: {_expr_to_str(parsed.right)} = "
                        f"{_expr_to_str(right_expanded)}",
                        "Algebraic expansion",
                    ),
                    ProofStep(
                        "Both sides are equal after expansion, so the identity holds",
                        "QED",
                    ),
                ]
                return ProofResult(
                    f"Proven: {_expr_to_str(parsed.left)} = {_expr_to_str(parsed.right)}",
                    steps,
                    True,
                    "algebraic expansion",
                )
    except (ParseError, EvalError) as e:
        logger.debug(repr(e))
    return None


# ═══════════════════════════════════════════════════════════════════════
# Part 5: Discovery Engine
# ═══════════════════════════════════════════════════════════════════════


@dataclass
class Conjecture:
    """A mathematical conjecture discovered by pattern analysis."""

    statement: str
    evidence: list[str] = field(default_factory=list)
    confidence: float = 0.0
    counterexample: str | None = None


@dataclass
class DiscoveryResult:
    """Result of a mathematical discovery process."""

    conjectures: list[Conjecture] = field(default_factory=list)
    summary: str = ""


def discover(pattern_type: str, n_examples: int = 20) -> DiscoveryResult:
    """Generate examples and look for mathematical patterns.

    This is how mathematicians discover new results: compute many
    examples, look for regularities, form conjectures, and test them.
    The discovery is genuinely computational — patterns are verified
    by actual computation, not hardcoded. The heuristics for which
    patterns to look for are hardcoded by topic keyword.
    """
    conjectures: list[Conjecture] = []
    lower = pattern_type.lower()

    # ── Discovery 1: Properties of even/odd sums ──
    if "even" in lower or "odd" in lower or "parity" in lower:
        conjectures.extend(_discover_parity(n_examples))
    # ── Discovery 2: Properties of prime numbers ──
    elif "prime" in lower:
        conjectures.extend(_discover_primes(n_examples))
    # ── Discovery 3: Sum of first n natural numbers ──
    elif "sum" in lower or "series" in lower or "triangular" in lower:
        conjectures.extend(_discover_sums(n_examples))
    # ── Discovery 4: Fibonacci patterns ──
    elif "fibonacci" in lower:
        conjectures.extend(_discover_fibonacci(n_examples))
    # ── Discovery 5: Divisibility patterns ──
    elif "divis" in lower:
        conjectures.extend(_discover_divisibility(n_examples))
    # ── Discovery 6: General pattern search on a sequence ──
    elif "sequence" in lower or "pattern" in lower:
        conjectures.extend(_discover_sequence(n_examples))

    summary = _build_discovery_summary(conjectures, n_examples, pattern_type)
    return DiscoveryResult(conjectures=conjectures, summary=summary)


def _discover_parity(n_examples: int) -> list[Conjecture]:
    """Discovery 1: properties of even/odd sums (verified by computation)."""
    conjectures: list[Conjecture] = []
    even_even_even = True
    odd_odd_even = True
    even_odd_odd = True

    for a in range(2, n_examples * 2, 2):  # even numbers
        for b in range(2, n_examples * 2, 2):  # even numbers
            if (a + b) % 2 != 0:
                even_even_even = False
                break
        if not even_even_even:
            break
    if even_even_even:
        even_even_evidence = ["2 + 4 = 6 (even), 2 + 6 = 8 (even), 4 + 8 = 12 (even)"]
        conjectures.append(
            Conjecture(
                "The sum of two even numbers is always even",
                even_even_evidence,
                1.0,
            )
        )

    for a in range(1, n_examples * 2, 2):  # odd numbers
        for b in range(1, n_examples * 2, 2):  # odd numbers
            if (a + b) % 2 != 0:
                odd_odd_even = False
                break
        if not odd_odd_even:
            break
    if odd_odd_even:
        odd_odd_evidence = ["1 + 3 = 4 (even), 3 + 5 = 8 (even), 1 + 7 = 8 (even)"]
        conjectures.append(
            Conjecture(
                "The sum of two odd numbers is always even",
                odd_odd_evidence,
                1.0,
            )
        )

    for a in range(2, n_examples * 2, 2):  # even
        for b in range(1, n_examples * 2, 2):  # odd
            if (a + b) % 2 == 0:
                even_odd_odd = False
                break
        if not even_odd_odd:
            break
    if even_odd_odd:
        even_odd_evidence = ["2 + 1 = 3 (odd), 4 + 3 = 7 (odd), 6 + 5 = 11 (odd)"]
        conjectures.append(
            Conjecture(
                "The sum of an even and an odd number is always odd",
                even_odd_evidence,
                1.0,
            )
        )
    return conjectures


def _discover_primes(n_examples: int) -> list[Conjecture]:
    """Discovery 2: prime-number patterns (all-odd, Goldbach, twin primes)."""
    conjectures: list[Conjecture] = []
    # Generate primes and look for patterns
    primes = _generate_primes(n_examples * 5)
    evidence = [f"First {n_examples} primes: {primes[:n_examples]}"]

    # Pattern: all primes > 2 are odd
    all_odd = all(p % 2 == 1 for p in primes if p > 2)
    if all_odd:
        evidence.append("3, 5, 7, 11, 13, 17, 19, 23, 29, 31 — all odd")
        conjectures.append(
            Conjecture(
                "All prime numbers greater than 2 are odd",
                evidence,
                1.0,
            )
        )

    # Pattern: Goldbach's conjecture (every even > 2 is sum of two primes)
    goldbach_holds = True
    goldbach_examples: list[str] = []
    prime_set = set(primes)
    for n in range(4, n_examples * 2, 2):
        found = False
        for p in primes:
            if p > n:
                break
            if (n - p) in prime_set:
                goldbach_examples.append(f"{n} = {p} + {n - p}")
                found = True
                break
        if not found:
            goldbach_holds = False
            break
    if goldbach_holds:
        evidence = goldbach_examples[:10]
        conjectures.append(
            Conjecture(
                "Every even number greater than 2 can be written as the sum of two primes"
                "(Goldbach's conjecture)",
                evidence,
                0.8,  # High confidence but unproven
            )
        )

    # Pattern: twin primes
    twin_primes = []
    for i in range(len(primes) - 1):
        if primes[i + 1] - primes[i] == 2:
            twin_primes.append((primes[i], primes[i + 1]))
    if len(twin_primes) > 3:
        evidence = [f"({a}, {b})" for a, b in twin_primes[:10]]
        conjectures.append(
            Conjecture(
                "There are infinitely many twin primes (twin prime conjecture)",
                evidence,
                0.5,  # Unproven, but strong evidence
            )
        )
    return conjectures


def _discover_sums(n_examples: int) -> list[Conjecture]:
    """Discovery 3: sum of first n naturals and sum of squares."""
    conjectures: list[Conjecture] = []
    evidence = []
    sums = []
    for n in range(1, n_examples + 1):
        s = n * (n + 1) // 2
        actual = sum(range(1, n + 1))
        sums.append((n, s, actual))
        evidence.append(f"1 + 2 + ... + {n} = {actual} = {n}×{n + 1}/2 = {s}")
    if all(s == a for _, s, a in sums):
        conjectures.append(
            Conjecture(
                "The sum of the first n natural numbers is n(n+1)/2",
                evidence[:10],
                1.0,
            )
        )

    # Also discover sum of squares
    sq_evidence = []
    sq_holds = True
    for n in range(1, min(n_examples, 15) + 1):
        actual = sum(k * k for k in range(1, n + 1))
        formula = n * (n + 1) * (2 * n + 1) // 6
        if actual != formula:
            sq_holds = False
            break
        sq_evidence.append(
            f"1² + 2² + ... + {n}² = {actual} = {n}({n + 1})({2 * n + 1})/6 = {formula}"
        )
    if sq_holds:
        conjectures.append(
            Conjecture(
                "The sum of the first n squares is n(n+1)(2n+1)/6",
                sq_evidence[:10],
                1.0,
            )
        )
    return conjectures


def _discover_fibonacci(n_examples: int) -> list[Conjecture]:
    """Discovery 4: Fibonacci recurrence and golden-ratio convergence."""
    conjectures: list[Conjecture] = []
    fib = [0, 1]
    while len(fib) < n_examples + 2:
        fib.append(fib[-1] + fib[-2])

    evidence = [f"Fibonacci sequence: {fib[:15]}"]

    # Pattern: F(n) = F(n-1) + F(n-2)
    conjectures.append(
        Conjecture(
            "Each Fibonacci number is the sum of the two preceding ones",
            evidence,
            1.0,
        )
    )

    # Pattern: ratio converges to golden ratio
    ratios = []
    for i in range(2, len(fib)):
        if fib[i - 1] != 0:
            ratios.append(fib[i] / fib[i - 1])
    if ratios:
        golden = (1 + math.sqrt(5)) / 2
        evidence.append(
            f"Ratios converge: {ratios[0]:.4f}, {ratios[5]:.4f}, {ratios[10]:.4f}, "
            f"... → {golden:.6f} (golden ratio)"
        )
        conjectures.append(
            Conjecture(
                "The ratio of consecutive Fibonacci numbers converges to the golden ratio (1 +"
                "√5)/2",
                evidence,
                1.0,
            )
        )
    return conjectures


def _discover_divisibility(n_examples: int) -> list[Conjecture]:
    """Discovery 5: digit-sum divisibility rules for 3 and 9."""
    conjectures: list[Conjecture] = []
    # Divisibility by 3: sum of digits divisible by 3
    evidence = []
    holds = True
    for n in range(3, n_examples * 10, 3):
        digit_sum = sum(int(d) for d in str(n))
        if digit_sum % 3 != 0:
            holds = False
            break
        evidence.append(f"{n}: digit sum = {digit_sum}, divisible by 3 ✓")
    if holds:
        conjectures.append(
            Conjecture(
                "A number is divisible by 3 if and only if the sum of its digits is divisible"
                "by 3",
                evidence[:10],
                1.0,
            )
        )

    # Divisibility by 9: sum of digits divisible by 9
    evidence9 = []
    holds9 = True
    for n in range(9, n_examples * 10, 9):
        digit_sum = sum(int(d) for d in str(n))
        if digit_sum % 9 != 0:
            holds9 = False
            break
        evidence9.append(f"{n}: digit sum = {digit_sum}, divisible by 9 ✓")
    if holds9:
        conjectures.append(
            Conjecture(
                "A number is divisible by 9 if and only if the sum of its digits is divisible"
                "by 9",
                evidence9[:10],
                1.0,
            )
        )
    return conjectures


def _discover_sequence(n_examples: int) -> list[Conjecture]:
    """Discovery 6: general pattern search — odd, square, triangular sequences."""
    conjectures: list[Conjecture] = []
    # Look for patterns in various sequences
    # Odd numbers: 1, 3, 5, 7, ... → nth term = 2n - 1
    evidence = []
    for n in range(1, n_examples + 1):
        term = 2 * n - 1
        evidence.append(f"a({n}) = {term}")
    conjectures.append(
        Conjecture(
            "The nth odd number is 2n - 1",
            evidence[:10],
            1.0,
        )
    )

    # Squares: 1, 4, 9, 16, ... → nth term = n²
    sq_evidence = []
    for n in range(1, n_examples + 1):
        sq_evidence.append(f"a({n}) = {n * n}")
    conjectures.append(
        Conjecture(
            "The nth square number is n²",
            sq_evidence[:10],
            1.0,
        )
    )

    # Triangular numbers: 1, 3, 6, 10, ... → nth term = n(n+1)/2
    tri_evidence = []
    for n in range(1, n_examples + 1):
        tri_evidence.append(f"a({n}) = {n * (n + 1) // 2}")
    conjectures.append(
        Conjecture(
            "The nth triangular number is n(n+1)/2",
            tri_evidence[:10],
            1.0,
        )
    )
    return conjectures


def _build_discovery_summary(
    conjectures: list[Conjecture], n_examples: int, pattern_type: str
) -> str:
    """Build the human-readable summary of a discovery run."""
    if conjectures:
        summary = f"Discovered {len(conjectures)} conjecture(s) from {n_examples} examples:\n"
        for i, c in enumerate(conjectures, 1):
            summary += f"\n{i}. {c.statement}\n"
            summary += f"   Confidence: {c.confidence:.0%}\n"
            if c.evidence:
                summary += f"   Evidence: {c.evidence[0]}\n"
            if c.counterexample:
                summary += f"   Counterexample: {c.counterexample}\n"
    else:
        summary = f"No patterns found in {n_examples} examples for '{pattern_type}'"
    return summary


def _generate_primes(n: int) -> list[int]:
    """Generate the first n prime numbers using the Sieve of Eratosthenes."""
    if n < 1:
        return []
    # Estimate upper bound
    upper = max(100, int(n * math.log(n) * 1.5))
    sieve = [True] * (upper + 1)
    sieve[0] = sieve[1] = False
    for i in range(2, int(math.sqrt(upper)) + 1):
        if sieve[i]:
            for j in range(i * i, upper + 1, i):
                sieve[j] = False
    return [i for i, is_prime in enumerate(sieve) if is_prime][:n]


# ═══════════════════════════════════════════════════════════════════════
# Part 6: Top-level interface
# ═══════════════════════════════════════════════════════════════════════


@dataclass
class MathResult:
    """Result of a math reasoning operation."""

    answer: str
    result_type: str  # "computation", "solution", "proof", "discovery"
    steps: list[str] = field(default_factory=list)
    success: bool = True


def _math_fragment(lower: str) -> str:
    """Extract the mathematical fragment of a question, dropping the
    natural-language shell so 'what is' doesn't read as variables."""
    for pattern in (
        r"(?:what\s+is|what's|calculate|compute|evaluate)\s+(.+)",
        r"(?:solve|find\s+x\s+in|find\s+the\s+value\s+of\s+x\s+in)\s+(.+)",
        r"(?:discover|find\s+patterns?\s+in|explore|investigate)\s+(.+)",
    ):
        match = re.match(pattern, lower)
        if match:
            return match.group(1).rstrip("?").strip()
    return lower


def _math_state(question: str) -> dict[str, Any]:
    """Structural signature of a math question.

    Operators, arity, and form are schema-level structure; the literal
    numbers are bindings — '2 + 3' and '5 + 7' are the same task
    wearing different values.
    """
    lower = question.lower().strip()
    fragment = _math_fragment(lower)
    tokens = tokenize(fragment)
    numbers = sum(1 for t in tokens if t.type == TokenType.NUMBER)
    idents = {t.value for t in tokens if t.type == TokenType.IDENT}
    functions = idents & _BUILTIN_FUNCTIONS.keys()
    variables = idents - _BUILTIN_FUNCTIONS.keys() - {
        "pi",
        "e",
        "infinity",
    }
    ops = {
        t.value
        for t in tokens
        if t.type
        in (
            TokenType.PLUS,
            TokenType.MINUS,
            TokenType.STAR,
            TokenType.SLASH,
            TokenType.CARET,
        )
    }
    has_eq = any(
        t.type
        in (
            TokenType.EQ,
            TokenType.LT,
            TokenType.GT,
            TokenType.LE,
            TokenType.GE,
            TokenType.NE,
        )
        for t in tokens
    )
    if lower.startswith(("prove ", "show that ")):
        form = "prove"
    elif re.match(
        r"(?:discover|find\s+patterns?\s+in|explore|investigate)\s", lower
    ):
        form = "discover"
    elif re.match(
        r"(?:solve|find\s+x\s+in|find\s+the\s+value\s+of\s+x\s+in)\s", lower
    ):
        form = "solve"
    elif re.match(
        r"(?:what\s+is|what's|calculate|compute|evaluate)\s", lower
    ):
        form = "compute"
    else:
        form = "expression"
    state: dict[str, Any] = {
        "math.form": form,
        "math.equation": has_eq,
        "math.numbers": min(numbers, 5),
        "math.variables": min(len(variables), 3),
        "math.functions": min(len(functions), 3),
    }
    for op in sorted(ops):
        state[f"math.op:{op}"] = True
    return state


def _record_math_episode(
    task_competence: Any,
    question: str,
    result: MathResult,
    salience: float | None,
) -> None:
    """Consolidate a math episode into the shared competence substrate.

    The math engine's own evaluation is the check, so verification is
    ``"solver"`` — honest provenance, not an external claim. Failed
    results record schema failures without consolidating a skill.
    Recognition runs *after* dispatch so non-math questions never
    litter the schema store.
    """
    from .competence import GoalCondition, ProcedureStep

    goal = GoalCondition("math.answered", "eq", 1)
    context = task_competence.recognize(
        domain="math",
        state=_math_state(question),
        goal_conditions=[goal],
        roles=("symbolic", "exact"),
    )
    steps = [
        ProcedureStep(
            action=result.result_type,
            family=result.result_type,
            description=step,
        )
        for step in result.steps
    ]
    if not steps:
        steps = [
            ProcedureStep(
                action=result.result_type,
                family=result.result_type,
                description=result.answer,
            )
        ]
    task_competence.record_episode(
        context,
        steps=steps,
        success=result.success,
        verification_score=1.0 if result.success else 0.0,
        goal_conditions=[goal],
        verification="solver",
        salience=salience,
    )


def try_math(
    question: str,
    network: Any = None,
    task_competence: Any = None,
    salience: float | None = None,
) -> MathResult | None:
    """Try to answer a question using mathematical reasoning.

    This is the entry point for the cognition engine. It detects
    what kind of math question is being asked and routes it to
    the appropriate engine (computation, solving, proof, discovery).

    If a concept network is provided, the simplification rules are
    gated by what Genesis has learned (see ``MathRuleRegistry``).
    Without a concept network, all rules are enabled (backward
    compatible).

    When ``task_competence`` is provided, each answered question is
    recorded as an episode: schemas accumulate which math families
    succeed or fail, and verified results consolidate as skills the
    concept network can reason about.

    Returns None if the question is not a math question.
    """
    lower = question.lower().strip()

    # Build rule registry from concept network if available
    enabled_rules: set[str] | None = None
    if network is not None:
        registry = MathRuleRegistry.from_concept_network(network)
        enabled_rules = registry.enabled_rules

    result = (
        # ── Computation: "what is 2 + 2?" ──
        _try_compute(lower, enabled_rules)
        # ── Bare expression: "2 + 2", "sqrt(16)" ──
        or _try_bare_expression(lower)
        # ── Equation solving: "solve 2x = 6" ──
        or _try_solve(lower, enabled_rules)
        # ── Proof requests: "prove that ..." ──
        or _try_proof(question, lower)
        # ── Discovery: "discover patterns in primes" ──
        or _try_discover(lower)
    )
    if result is not None and task_competence is not None:
        _record_math_episode(task_competence, question, result, salience)
    return result


def _try_compute(lower: str, enabled_rules: set[str] | None) -> MathResult | None:
    """Detect 'what is 2 + 2' style computation requests."""
    # Look for arithmetic expressions
    compute_match = re.match(
        r"(?:what\s+is|what's|calculate|compute|evaluate)\s+(.+)",
        lower,
    )
    if compute_match:
        expr_str = compute_match.group(1).rstrip("?")
        # Don't treat definitions as computations
        if not _looks_like_definition(expr_str):
            try:
                parsed = parse_expression(expr_str)
                if isinstance(parsed, Equation):
                    # It's an equation — try to solve or verify
                    result = solve_equation(parsed, enabled_rules)
                    if result.success:
                        return MathResult(
                            result.solution,
                            "solution",
                            [f"{s.description}: {s.expression}" for s in result.steps],
                        )
                else:
                    # It's an expression — evaluate it
                    value = evaluate(parsed)
                    return MathResult(
                        f"{format_number(value)}",
                        "computation",
                        [f"{_expr_to_str(parsed)} = {format_number(value)}"],
                    )
            except (ParseError, EvalError) as e:
                logger.debug(repr(e))
    return None


def _try_bare_expression(lower: str) -> MathResult | None:
    """Detect bare arithmetic expressions like '2 + 2', 'sqrt(16)'."""
    if re.match(r"^[\d\s+\-*/^().,a-z_]+[?]?$", lower):
        expr_str = lower.rstrip("?").strip()
        if any(c.isdigit() for c in expr_str) and any(c in "+-*/^" for c in expr_str):
            try:
                parsed = parse_expression(expr_str)
                if isinstance(parsed, (BinOp, UnaryOp, FuncCall, Num)):
                    value = evaluate(parsed)
                    return MathResult(
                        f"{format_number(value)}",
                        "computation",
                        [f"{_expr_to_str(parsed)} = {format_number(value)}"],
                    )
            except (ParseError, EvalError) as e:
                logger.debug(repr(e))
    return None


def _try_solve(lower: str, enabled_rules: set[str] | None) -> MathResult | None:
    """Detect equation-solving requests like 'solve 2x = 6'."""
    solve_match = re.match(
        r"(?:solve|find\s+x\s+in|find\s+the\s+value\s+of\s+x\s+in)\s+(.+)",
        lower,
    )
    if solve_match:
        eq_str = solve_match.group(1).rstrip("?")
        try:
            parsed = parse_expression(eq_str)
            if isinstance(parsed, Equation):
                result = solve_equation(parsed, enabled_rules)
                if result.success:
                    return MathResult(
                        result.solution,
                        "solution",
                        [f"{s.description}: {s.expression}" for s in result.steps],
                    )
        except (ParseError, EvalError) as e:
            logger.debug(repr(e))
    return None


def _try_proof(question: str, lower: str) -> MathResult | None:
    """Detect proof requests like 'prove that ...'."""
    if lower.startswith("prove ") or lower.startswith("show that "):
        result = prove(question)
        return MathResult(
            result.conclusion,
            "proof",
            [f"{s.statement} ({s.justification})" for s in result.steps],
            result.success,
        )
    return None


def _try_discover(lower: str) -> MathResult | None:
    """Detect discovery requests like 'discover patterns in primes'."""
    discover_match = re.match(
        r"(?:discover|find\s+patterns?\s+in|explore|investigate)\s+(.+)",
        lower,
    )
    if discover_match:
        topic = discover_match.group(1).rstrip("?")
        result = discover(topic)
        return MathResult(
            result.summary,
            "discovery",
            [],
            len(result.conjectures) > 0,
        )
    return None


def _looks_like_definition(text: str) -> bool:
    """Check if text looks like a definition rather than a computation.

    "what is calculus" is a definition, "what is 2+2" is a computation.
    """
    # If it has digits and operators, it's likely a computation
    has_digits = any(c.isdigit() for c in text)
    has_ops = any(c in "+-*/^=" for c in text)
    if has_digits and has_ops:
        return False
    # If it has no digits, it's likely a definition
    if not has_digits:
        return True
    # If it has digits but no operators, could be either
    return False
