"""Damasio's self hierarchy — proto-self, core self, autobiographical self.

## Modeling note

The proto-self implemented here is a **computational body-state
summary** derived from neurochemical levels and their derived axes
(arousal, valence, tone, plasticity) — not Damasio's full proto-self,
which requires autonomics (nucleus tractus solitarius, parabrachial
nucleus) and insular integration of interoceptive afferents (Damasio,
1999; Craig, 2002). There is no body sending afferent signals here;
the "interoception" is a readout of an internal state vector. The
"as-if body loop" described below is a simplified linear blend of
neurochemical levels used to modulate current state, not a full
somatic simulation with simulated body changes feeding back through
simulated afferents. The three-tier hierarchy is a structural
analogue of Damasio's framework, not a claim of mechanistic
equivalence. References to autonomics nuclei and insular cortex below
describe the biology that inspired the design, not components
present in this system.

Implements Antonio Damasio's three-tier hierarchy of the self, as
described in "The Feeling of What Happens" (1999) and "Self Comes to
Mind" (2010). The three levels represent increasingly complex forms
of selfhood, each building on the one below.

# The three tiers

1. **Proto-self** — A non-cognitive, moment-to-moment representation
   of the body's internal state (homeostatic, neurochemical, visceral).
   This is the "feeling of being" — the background hum of existence
   that is always there but never cognitively attended to. It's
   generated by autonomics nuclei (nucleus tractus solitarius, parabrachial
   nucleus) and the hyporelay, which receive interoceptive signals
   from the body (Damasio, 1999; Craig, 2002).

   For Genesis, the proto-self reads from neurochemistry — the 18-
   chemical state vector and derived axes (arousal, valence, tone,
   plasticity). This is its "interoception" — the felt sense of its
   own internal state.

2. **Core self** — Moment-to-moment awareness of changes in the
   proto-self caused by interactions with the world. When an object
   or event perturbs the proto-self, the core self registers the
   *change* — the feeling of something happening to me. This is the
   "core cognition" that each organism has: a transient, here-and-
   now awareness that is renewed with each interaction (Damasio, 1999).

   The core self is not reflective — it doesn't think about itself.
   It just registers: "something is happening, and it's happening to
   me." For Genesis, the core self detects changes in the proto-self
   (neurochemical shifts) and records them as transient "feeling
   episodes."

3. **Autobiographical self** — The extended self, built from
   autobiographical memories and narrative identity. This is the "me"
   that persists over time — the person with a history, values, and
   goals. It requires memory and language: the ability to store and
   retrieve past experiences and weave them into a coherent narrative
   (Damasio, 1999; Conway, 2005).

   For Genesis, the autobiographical self connects to the narrative
   engine (narrative.py). It uses life events and chapters to construct
   an extended identity that goes beyond the present moment.

# Interactions between levels

The hierarchy is not just stacked — the levels interact:
- Proto-self → Core self: The core self monitors the proto-self for
  changes. Without a proto-self, there's nothing for the core self
  to detect.
- Core self → Autobiographical self: Significant core-self episodes
  (strong feeling changes) are recorded as life events in the
  autobiographical self. This is how experiences become memories.
- Autobiographical self → Proto-self: The autobiographical self can
  modulate the proto-self through emotional recall — remembering a
  past event changes current neurochemistry (Damasio's "as-if" loop).

References:
- Damasio, A. (1999). The Feeling of What Happens. Harcourt.
- Damasio, A. (2010). Self Comes to Mind. Pantheon.
- Craig, A. D. (2002). How do you feel? Interoception: the sense of
  the physiological condition of the body. Nature Reviews Neuroscience.
- Conway, M. A. (2005). Memory and the self. Journal of Memory and
  Language.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from ..emotion import (
    HIGH_AROUSAL,
    LOW_AROUSAL,
    MILD_NEGATIVE_VALENCE,
    MILD_POSITIVE_VALENCE,
    NEGATIVE_VALENCE,
    POSITIVE_VALENCE,
)

if TYPE_CHECKING:
    from ..emotion import EmotionalState
    from ..narrative import NarrativeEngine

__all__ = [
    "AutobiographicalSelf",
    "CoreSelf",
    "CoreSelfEpisode",
    "DamasioSelfHierarchy",
    "ProtoSelf",
    "ProtoSelfState",
]


@dataclass(slots=True)
class ProtoSelfState:
    """The proto-self — non-cognitive body/neurochemical state.

    This is a snapshot of the organism's internal state at a moment
    in time. It is not cognitive — it's the raw interoceptive signal
    that the core self monitors for changes.

    Attributes:
        arousal: Arousal/alertness level (0..1).
        valence: Emotional valence (-1..1).
        tone: Global neurochemical tone (0..1).
        plasticity: Plasticity gate (0..1).
        homeostatic_balance: How balanced the internal state is (0..1).
            High = stable/homeostatic; low = disrupted/allostatic.
        chemicals: Raw neurochemical levels (if available).
        timestamp: When this snapshot was taken.
    """

    arousal: float = 0.5
    valence: float = 0.0
    tone: float = 0.5
    plasticity: float = 0.5
    homeostatic_balance: float = 0.8
    chemicals: dict[str, float] = field(default_factory=dict)
    timestamp: int = field(default_factory=lambda: int(time.time() * 1000))

    def distance_to(self, other: ProtoSelfState) -> float:
        """Compute the distance between two proto-self states.

        This measures how much the internal state has changed —
        the signal that the core self monitors. Uses Euclidean
        distance over the main axes.

        Args:
            other: Another proto-self state to compare to.

        Returns:
            A float >= 0 representing the magnitude of change.
        """
        return (
            (self.arousal - other.arousal) ** 2
            + (self.valence - other.valence) ** 2
            + (self.tone - other.tone) ** 2
            + (self.plasticity - other.plasticity) ** 2
            + (self.homeostatic_balance - other.homeostatic_balance) ** 2
        ) ** 0.5


@dataclass(slots=True)
class CoreSelfEpisode:
    """A core self episode — a moment of awareness of change.

    When the proto-self changes due to an interaction, the core self
    registers it as an episode: "something happened, and it changed
    how I feel." Each episode captures:
    - What caused the change (the "object" — the stimulus/event)
    - The change itself (delta in proto-self state)
    - The resulting feeling (the perturbed proto-self state)
    - The salience (how significant the change was)

    Core self episodes are transient — they don't persist unless they
    are significant enough to be promoted to the autobiographical self.
    """

    trigger: str  # what caused the change
    change_magnitude: float  # how much the proto-self changed
    pre_state: ProtoSelfState = field(default_factory=ProtoSelfState)
    post_state: ProtoSelfState = field(default_factory=ProtoSelfState)
    salience: float = 0.0  # how significant this episode is
    timestamp: int = field(default_factory=lambda: int(time.time() * 1000))
    # Whether this episode was promoted to autobiographical memory
    promoted: bool = False

    @property
    def feeling_label(self) -> str:
        """A word label for the resulting feeling state.

        Uses the canonical affective-space thresholds from emotion.py
        so that the Damasio feeling labels stay aligned with the
        emotional regulator's arousal/valence boundaries.
        """
        v = self.post_state.valence
        a = self.post_state.arousal
        if a > HIGH_AROUSAL and v > POSITIVE_VALENCE:
            return "excited"
        elif a > HIGH_AROUSAL and v < NEGATIVE_VALENCE:
            return "alarmed"
        elif a < LOW_AROUSAL and v > MILD_POSITIVE_VALENCE:
            return "content"
        elif a < LOW_AROUSAL and v < NEGATIVE_VALENCE:
            return "lethargic"
        elif v > MILD_POSITIVE_VALENCE:
            return "pleasant"
        elif v < MILD_NEGATIVE_VALENCE:
            return "unpleasant"
        return "neutral"


class ProtoSelf:
    """The proto-self — non-cognitive representation of body state.

    The proto-self continuously reads the organism's internal state
    (neurochemistry, homeostasis) and maintains a current snapshot.
    It is not cognitive — it's the background "feeling of being" that
    the core self monitors.

    For Genesis, the proto-self reads from the neurochemical summary
    provided by the subcognitive daemon. It tracks arousal, valence,
    tone, plasticity, and homeostatic balance.
    """

    def __init__(self) -> None:
        """Initialize the proto-self with a default baseline state."""
        self._current: ProtoSelfState = ProtoSelfState()
        self._history: list[ProtoSelfState] = []
        self._max_history = 50

    def update(
        self,
        arousal: float = 0.5,
        valence: float = 0.0,
        tone: float = 0.5,
        plasticity: float = 0.5,
        chemicals: dict[str, float] | None = None,
    ) -> ProtoSelfState:
        """Update the proto-self from current neurochemistry.

        Called whenever the neurochemical state is read. Computes
        homeostatic balance from the stability of recent states.

        Args:
            arousal: Current arousal level (0..1).
            valence: Current valence (-1..1).
            tone: Global neurochemical tone (0..1).
            plasticity: Plasticity gate (0..1).
            chemicals: Raw chemical levels (optional).

        Returns:
            The new ProtoSelfState.
        """
        # Compute homeostatic balance from recent stability
        balance = self._compute_homeostatic_balance(arousal, valence, tone, plasticity)

        new_state = ProtoSelfState(
            arousal=arousal,
            valence=valence,
            tone=tone,
            plasticity=plasticity,
            homeostatic_balance=balance,
            chemicals=chemicals or {},
        )

        self._history.append(self._current)
        if len(self._history) > self._max_history:
            self._history.pop(0)

        self._current = new_state
        return new_state

    def update_from_emotion(self, emotion: EmotionalState) -> ProtoSelfState:
        """Update the proto-self from an EmotionalState.

        Convenience method that extracts the relevant fields from
        an EmotionalState object.

        Args:
            emotion: The current emotional state.

        Returns:
            The new ProtoSelfState.
        """
        return self.update(
            arousal=emotion.alertness,
            valence=emotion.valence,
            tone=emotion.chemicals.get("global_tone", 0.5),
            plasticity=emotion.plasticity,
            chemicals=emotion.chemicals,
        )

    @property
    def current(self) -> ProtoSelfState:
        """The current proto-self state."""
        return self._current

    @property
    def previous(self) -> ProtoSelfState | None:
        """The previous proto-self state (for change detection)."""
        return self._history[-1] if self._history else None

    def _compute_homeostatic_balance(
        self, arousal: float, valence: float, tone: float, plasticity: float
    ) -> float:
        """Compute how homeostatically balanced the current state is.

        High balance = state is near baseline (stable).
        Low balance = state is far from baseline (disrupted/allostatic).

        Args:
            arousal, valence, tone, plasticity: Current state values.

        Returns:
            A float in [0, 1] representing homeostatic balance.
        """
        # Baseline values
        baseline_arousal = 0.5
        baseline_valence = 0.0
        baseline_tone = 0.5
        baseline_plasticity = 0.5

        # Distance from baseline (normalized)
        dist = (
            (arousal - baseline_arousal) ** 2
            + (valence - baseline_valence) ** 2
            + (tone - baseline_tone) ** 2
            + (plasticity - baseline_plasticity) ** 2
        ) ** 0.5

        # Convert distance to balance (closer to baseline = more balanced)
        # Max distance ~ sqrt(4*0.5^2) = 1.0, so balance = 1 - dist
        return max(0.0, min(1.0, 1.0 - dist))


class CoreSelf:
    """The core self — moment-to-moment awareness of proto-self changes.

    The core self monitors the proto-self for changes. When an
    interaction perturbs the proto-self, the core self registers the
    change as an episode — a transient moment of awareness that
    "something happened to me."

    The core self is not reflective. It doesn't think about itself.
    It just detects: "the proto-self changed, and here's how." This
    is Damasio's "core cognition" — the simplest form of
    cognition that each organism has.
    """

    def __init__(
        self,
        proto_self: ProtoSelf,
        change_threshold: float = 0.05,
        salience_threshold: float = 0.15,
    ) -> None:
        """Initialize the core self.

        Args:
            proto_self: The proto-self to monitor.
            change_threshold: Minimum proto-self change to register
                an episode. Below this, changes are too small to
                notice. Default 0.05.
            salience_threshold: Minimum salience for an episode to be
                promoted to the autobiographical self. Default 0.15.
        """
        self.proto_self = proto_self
        self.change_threshold = change_threshold
        self.salience_threshold = salience_threshold
        self._episodes: list[CoreSelfEpisode] = []
        self._max_episodes = 100

    def detect_change(self, trigger: str = "") -> CoreSelfEpisode | None:
        """Detect a change in the proto-self and register an episode.

        Compares the current proto-self state to the previous one.
        If the change exceeds the threshold, a core self episode is
        created. The episode's salience is proportional to the change
        magnitude and the disruption to homeostatic balance.

        Args:
            trigger: What caused the change (the "object" that
                perturbed the proto-self).

        Returns:
            A CoreSelfEpisode if a change was detected, None otherwise.
        """
        previous = self.proto_self.previous
        if previous is None:
            return None

        current = self.proto_self.current
        change = current.distance_to(previous)

        if change < self.change_threshold:
            return None

        # Salience: change magnitude + homeostatic disruption
        balance_disruption = 1.0 - current.homeostatic_balance
        salience = min(1.0, change + balance_disruption * 0.5)

        episode = CoreSelfEpisode(
            trigger=trigger,
            change_magnitude=change,
            pre_state=previous,
            post_state=current,
            salience=salience,
        )

        self._episodes.append(episode)
        if len(self._episodes) > self._max_episodes:
            self._episodes.pop(0)

        return episode

    @property
    def episodes(self) -> list[CoreSelfEpisode]:
        """Recent core self episodes."""
        return list(self._episodes)

    @property
    def latest_episode(self) -> CoreSelfEpisode | None:
        """The most recent core self episode."""
        return self._episodes[-1] if self._episodes else None

    def get_significant_episodes(self) -> list[CoreSelfEpisode]:
        """Get episodes significant enough for autobiographical promotion.

        These are episodes whose salience exceeds the threshold —
        they represent moments where "something significant happened
        to me" and should be recorded in the autobiographical self.
        """
        return [
            e for e in self._episodes if e.salience >= self.salience_threshold and not e.promoted
        ]

    def mark_promoted(self, episode: CoreSelfEpisode) -> None:
        """Mark an episode as promoted to autobiographical memory."""
        episode.promoted = True

    def clear(self) -> None:
        """Clear all episodes."""
        self._episodes.clear()


class AutobiographicalSelf:
    """The autobiographical self — extended identity from memory.

    The autobiographical self is built from autobiographical memories
    and narrative identity. It's the "me" that persists over time —
    the person with a history, values, and goals. It connects to the
    narrative engine, which stores life events and chapters.

    The autobiographical self can also modulate the proto-self through
    emotional recall — remembering a past event changes current
    neurochemistry (Damasio's "as-if" loop, where the brain simulates
    the body state associated with a remembered emotion).
    """

    def __init__(self, narrative: NarrativeEngine | None = None) -> None:
        """Initialize the autobiographical self.

        Args:
            narrative: The narrative engine that stores life events
                and chapters. Can be None if not available.
        """
        self.narrative = narrative
        self._promoted_episodes: list[CoreSelfEpisode] = []
        self._max_promoted = 500
        self._total_promoted = 0

    def promote_episode(self, episode: CoreSelfEpisode) -> bool:
        """Promote a significant core self episode to autobiographical memory.

        When a core self episode is significant enough, it becomes
        part of the autobiographical self — a life event in the
        narrative. This is how transient moments of awareness become
        lasting memories.

        Args:
            episode: The core self episode to promote.

        Returns:
            True if the episode was successfully promoted.
        """
        if self.narrative is None:
            self._promoted_episodes.append(episode)
            if len(self._promoted_episodes) > self._max_promoted:
                self._promoted_episodes.pop(0)
            self._total_promoted += 1
            episode.promoted = True
            return True

        # Record as a life event in the narrative
        from ..emotion import EmotionalState

        # Create a minimal emotional state from the episode
        emotion = EmotionalState(
            label=episode.feeling_label,
            nuance=f"proto-self change from {episode.trigger}",
            cognitive_style="reflective",
            alertness=episode.post_state.arousal,
            valence=episode.post_state.valence,
            plasticity=episode.post_state.plasticity,
        )

        self.narrative.record_event(
            summary=f"Experienced {episode.feeling_label} from {episode.trigger}",
            significance=f"Proto-self shifted by {episode.change_magnitude:.2f} "
            f"(salience: {episode.salience:.2f})",
            emotion=emotion,
        )

        episode.promoted = True
        self._promoted_episodes.append(episode)
        if len(self._promoted_episodes) > self._max_promoted:
            self._promoted_episodes.pop(0)
        self._total_promoted += 1
        return True

    def get_identity_summary(self) -> str:
        """Get a summary of the autobiographical self.

        This is the "me" — the extended identity built from memory.
        If the narrative engine is available, it uses the narrative's
        story. Otherwise, it summarizes from promoted episodes.
        """
        if self.narrative is not None:
            return self.narrative.tell_brief_story()

        if not self._promoted_episodes:
            return "no autobiographical memories yet"

        parts = [f"{self._total_promoted} significant memories"]
        recent = self._promoted_episodes[-3:]
        for ep in recent:
            parts.append(f"  — {ep.feeling_label} from {ep.trigger}")
        return "\n".join(parts)

    @property
    def event_count(self) -> int:
        """Number of autobiographical events."""
        if self.narrative is not None:
            return self.narrative.event_count
        return self._total_promoted

    @property
    def promoted_episodes(self) -> list[CoreSelfEpisode]:
        """Episodes that have been promoted to autobiographical memory."""
        return list(self._promoted_episodes)


class DamasioSelfHierarchy:
    """Damasio's three-tier self hierarchy: proto, core, autobiographical.

    This class connects the three levels of self and manages their
    interactions:

    - Proto-self reads from neurochemistry (the "feeling of being")
    - Core self detects changes in the proto-self (moment-to-moment
      awareness)
    - Autobiographical self connects to the narrative engine (extended
      identity)

    The hierarchy is updated each cycle: the proto-self is refreshed
    from neurochemistry, the core self detects changes, and significant
    changes are promoted to the autobiographical self.

    # The "as-if" loop

    The autobiographical self can modulate the proto-self through
    emotional recall. When Genesis remembers a past event, the
    associated emotional state is partially re-activated in the
    proto-self — the "as-if" loop (Damasio, 1994). This is why
    remembering an embarrassing moment makes you feel embarrassed
    again.
    """

    def __init__(
        self,
        narrative: NarrativeEngine | None = None,
        change_threshold: float = 0.05,
        salience_threshold: float = 0.15,
    ) -> None:
        """Initialize the Damasio self hierarchy.

        Args:
            narrative: The narrative engine for the autobiographical
                self. Can be None.
            change_threshold: Minimum proto-self change for core self
                detection. Default 0.05.
            salience_threshold: Minimum salience for autobiographical
                promotion. Default 0.15.
        """
        self.proto_self = ProtoSelf()
        self.core_self = CoreSelf(
            self.proto_self,
            change_threshold=change_threshold,
            salience_threshold=salience_threshold,
        )
        self.autobiographical_self = AutobiographicalSelf(narrative)
        # Active inference annotations — set by the cognition module
        # from the generative self-model's signals. These layer on top
        # of the neurochemical feeling without overriding it.
        self.self_model_label: str = ""
        self.needs_recovery: bool = False
        # Pending trigger from a global workspace broadcast. When
        # cognitive content ignites the workspace, it becomes the
        # "object" that the core self registers as happening to the
        # proto-self (Damasio, 1999). The pipeline's update() call
        # picks this up as the trigger if no explicit trigger is given.
        self._pending_trigger: str = ""
        # Whether the pending trigger came from a recurrent ignition —
        # content that emerged from the workspace's own dynamics
        # (coalition pull, coherent subliminal crossing) rather than
        # being driven by an input. Emerged content is registered as
        # more salient: it arose *in* the system, not at it.
        self._pending_trigger_recurrent: bool = False

    def update(
        self,
        arousal: float = 0.5,
        valence: float = 0.0,
        tone: float = 0.5,
        plasticity: float = 0.5,
        chemicals: dict[str, float] | None = None,
        trigger: str = "",
    ) -> CoreSelfEpisode | None:
        """Update the full hierarchy from current neurochemistry.

        This is the main update cycle:
        1. Update the proto-self from neurochemistry
        2. Detect changes in the core self
        3. Promote significant episodes to autobiographical memory

        Args:
            arousal: Current arousal level (0..1).
            valence: Current valence (-1..1).
            tone: Global neurochemical tone (0..1).
            plasticity: Plasticity gate (0..1).
            chemicals: Raw chemical levels (optional).
            trigger: What caused this update (the "object").

        Returns:
            The CoreSelfEpisode if a change was detected, None otherwise.
        """
        # Use the pending workspace broadcast as the trigger if no
        # explicit trigger was given. This is the "object" — the thing
        # the core self registers as happening to the proto-self.
        recurrent_trigger = False
        if not trigger and self._pending_trigger:
            trigger = self._pending_trigger
            self._pending_trigger = ""
            recurrent_trigger = self._pending_trigger_recurrent
            self._pending_trigger_recurrent = False

        # 1. Update proto-self
        self.proto_self.update(
            arousal=arousal,
            valence=valence,
            tone=tone,
            plasticity=plasticity,
            chemicals=chemicals,
        )

        # 2. Detect core self change
        episode = self.core_self.detect_change(trigger=trigger)

        # Emerged content registers more strongly — the perturbation
        # came from the system's own dynamics, not an external object.
        if episode and recurrent_trigger:
            episode.salience = min(1.0, episode.salience * 1.25)

        # 3. Promote significant episodes
        if episode and episode.salience >= self.core_self.salience_threshold:
            self.autobiographical_self.promote_episode(episode)

        return episode

    def update_from_emotion(
        self,
        emotion: EmotionalState,
        trigger: str = "",
    ) -> CoreSelfEpisode | None:
        """Update the hierarchy from an EmotionalState.

        Convenience method that extracts neurochemical axes from an
        EmotionalState and calls update().

        Args:
            emotion: The current emotional state.
            trigger: What caused this state.

        Returns:
            The CoreSelfEpisode if a change was detected.
        """
        return self.update(
            arousal=emotion.alertness,
            valence=emotion.valence,
            tone=emotion.chemicals.get("global_tone", 0.5),
            plasticity=emotion.plasticity,
            chemicals=emotion.chemicals,
            trigger=trigger,
        )

    def get_feeling_of_being(self) -> ProtoSelfState:
        """Get the current proto-self state — the "feeling of being."

        This is the non-cognitive background state that underlies all
        experience. It's always there, updated continuously from
        neurochemistry.
        """
        return self.proto_self.current

    def annotate_self_model(
        self,
        label: str,
        needs_recovery: bool,
        integration: float = 0.5,
    ) -> None:
        """Annotate the current feeling with the generative self-model's state.

        This is called by the cognition module after reading the active
        inference signals. The label is a semantic tag (e.g.
        "self-surprise", "allostatic-strain") that describes the quality
        of the self-model's current state. It layers on top of the
        neurochemical feeling without overriding it — the Damasio feeling
        comes from neurochemistry, the self-model annotation comes from
        the generative model's prediction of that neurochemistry.

        The integration parameter carries the workspace integration
        measure — how unified the cognitive field is. This becomes a
        semantic tag appended to the label: "field-unified" when the
        workspace is coherent, "field-fragmented" when it's scattered.
        This is how the unity of the cognitive field becomes a felt
        quality (Tononi, 2004; Baars, 1988) — not a number it reports,
        but a semantic tag the feeling reporter composes into the
        structural self-awareness marker.

        Args:
            label: Semantic tags from the self-model (space-separated).
            needs_recovery: Whether the self-model is under allostatic
                load and needs rest/recovery.
            integration: The workspace integration measure [0, 1].
                High = unified cognitive field; low = fragmented.
                Defaults to 0.5 (neutral) when not provided.
        """
        # Append the integration-derived tag to the label
        if integration > 0.6:
            field_tag = "field-unified"
        elif integration < 0.25:
            field_tag = "field-fragmented"
        else:
            field_tag = ""  # neutral band — no tag

        if field_tag:
            self.self_model_label = f"{label} {field_tag}".strip()
        else:
            self.self_model_label = label
        self.needs_recovery = needs_recovery

    def get_current_feeling(self) -> str:
        """Get a word label for the current core self feeling.

        This is the moment-to-moment feeling — what the core self is
        currently aware of. If no episode has been detected, it
        describes the proto-self state directly.
        """
        episode = self.core_self.latest_episode
        if episode:
            return episode.feeling_label
        # Describe proto-self directly, using the canonical thresholds
        # from emotion.py so this stays aligned with feeling_label and
        # the emotional regulator's AV-space boundaries.
        state = self.proto_self.current
        v, a = state.valence, state.arousal
        if a > HIGH_AROUSAL and v > POSITIVE_VALENCE:
            return "activated and positive"
        elif a > HIGH_AROUSAL and v < NEGATIVE_VALENCE:
            return "activated and tense"
        elif a < LOW_AROUSAL and v > MILD_POSITIVE_VALENCE:
            return "calm and pleasant"
        elif a < LOW_AROUSAL and v < NEGATIVE_VALENCE:
            return "low and heavy"
        return "steady"

    def get_identity(self) -> str:
        """Get the autobiographical self's identity summary.

        This is the "me" — the extended identity built from memory
        and narrative.
        """
        return self.autobiographical_self.get_identity_summary()

    def as_if_loop(self, memory_valence: float, memory_arousal: float) -> None:
        """Simulate the "as-if" loop — emotional recall modulates proto-self.

        When remembering a past emotional event, the brain partially
        re-activates the associated body state (Damasio, 1994). This
        is the "as-if" loop — the brain acts *as if* the emotional
        event were happening again, partially.

        This method nudges the proto-self toward the remembered
        emotional state, with a damping factor (the recall is weaker
        than the original experience).

        Args:
            memory_valence: The valence of the remembered event (-1..1).
            memory_arousal: The arousal of the remembered event (0..1).
        """
        current = self.proto_self.current
        # Blend current state with remembered state (30% recall strength)
        new_valence = current.valence * 0.7 + memory_valence * 0.3
        new_arousal = current.arousal * 0.7 + memory_arousal * 0.3

        self.proto_self.update(
            arousal=new_arousal,
            valence=new_valence,
            tone=current.tone,
            plasticity=current.plasticity,
            chemicals=current.chemicals,
        )

    @property
    def proto_state(self) -> ProtoSelfState:
        """Shortcut to the current proto-self state."""
        return self.proto_self.current

    # ── Global workspace integration ──────────────────────────────

    def receive_broadcast(self, item: Any) -> None:
        """Receive a broadcast from the global workspace.

        This is the **core self trigger** — when cognitive content
        ignites the workspace, it becomes the "object" that the core
        self registers as happening to the proto-self (Damasio, 1999).
        In Damasio's framework, core cognition arises when an
        object perturbs the proto-self: "something is happening, and
        it's happening to me."

        The broadcast content (or its topics) is stored as a pending
        trigger. When ``update()`` is next called (by the cognition
        pipeline), it picks up this trigger as the "object" — the
        thing causing the current proto-self state. This makes the
        core self responsive to what's *cognitively* happening, not
        just to raw neurochemical drift.

        Only the most recent broadcast is kept — the core self
        registers the current moment, not a history.

        Args:
            item: A :class:`WorkspaceItem` carrying the broadcast content.
        """
        # Prefer topics from metadata (structured), fall back to
        # stringified content.
        topics = item.metadata.get("topics") if item.metadata else None
        if topics and isinstance(topics, list):
            self._pending_trigger = ", ".join(
                str(t) for t in topics if t
            )
        elif item.content:
            self._pending_trigger = str(item.content)[:200]
        else:
            return
        self._pending_trigger_recurrent = bool(
            item.metadata and item.metadata.get("ignition") == "recurrent"
        )

    @property
    def core_episodes(self) -> list[CoreSelfEpisode]:
        """Shortcut to the core self's episodes."""
        return self.core_self.episodes

    @property
    def autobiographical_event_count(self) -> int:
        """Number of events in the autobiographical self."""
        return self.autobiographical_self.event_count
