#!/bin/bash
# Install the Genesis sudoers rule with the correct username and path.
#
# Usage: sudo bash scripts/install_sudoers.sh
#
# This script detects the current user and the absolute paths to the
# privileged helper scripts (cpufreq_helper.sh, rtc_wake_helper.sh),
# generates a sudoers rule, and installs it to /etc/sudoers.d/genesis.

set -euo pipefail

# Must be run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "Error: must be run as root. Use: sudo bash scripts/install_sudoers.sh"
    exit 1
fi

# Detect the real user (the one who invoked sudo)
REAL_USER="${SUDO_USER:-${USER:-}}"

# Refuse to install a NOPASSWD sudo rule for root or an empty user —
# this would either be a no-op or grant overly broad privileges.
if [ -z "$REAL_USER" ] || [ "$REAL_USER" = "root" ]; then
    echo "Error: cannot determine the non-root user to grant sudo access to."
    echo "If you ran this script directly as root (not via sudo), pass the"
    echo "target username explicitly: REAL_USER=yourname sudo bash scripts/install_sudoers.sh"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
HELPER_PATH="$SCRIPT_DIR/cpufreq_helper.sh"
RTC_HELPER_PATH="$SCRIPT_DIR/rtc_wake_helper.sh"

for helper in "$HELPER_PATH" "$RTC_HELPER_PATH"; do
    if [ ! -f "$helper" ]; then
        echo "Error: helper not found at $helper"
        exit 1
    fi
    # Verify the helper is executable
    if [ ! -x "$helper" ]; then
        chmod +x "$helper"
    fi
done

# Generate and install the sudoers rule
echo "Installing sudoers rule for user '$REAL_USER'"
cat > /etc/sudoers.d/genesis << EOF
# Generated by scripts/install_sudoers.sh
# Allows $REAL_USER to run the Genesis privileged helpers without a password:
#   cpufreq_helper.sh  — CPU frequency/governor/boost policy
#   rtc_wake_helper.sh — RTC wake alarm (scheduling resume from suspend)
$REAL_USER ALL=(root) NOPASSWD: $HELPER_PATH *
$REAL_USER ALL=(root) NOPASSWD: $RTC_HELPER_PATH *
EOF

chmod 440 /etc/sudoers.d/genesis

# Verify syntax
if visudo -c -f /etc/sudoers.d/genesis; then
    echo "Success. Genesis can now control CPU frequency and arm the RTC wake alarm via sudo."
else
    echo "Error: sudoers syntax check failed. Removing the rule."
    rm -f /etc/sudoers.d/genesis
    exit 1
fi
