"""Brainstem — arousal, sleep-wake switching, and the REM oscillator.

════════════════════════════════════════════════════════════════════════
ANATOMY AND FUNCTION
════════════════════════════════════════════════════════════════════════

The autonomics (midbrain, pons, medulla) is the oldest part of the
brain. It sits below the diencephalon and contains the ascending
reticular activating system (ARAS) — the machinery that decides
whether the cortex is awake, dreaming, or in deep sleep. The subsystems
process information; the autonomics decides whether there is a mind
awake to process it.

Key functions:
    - Arousal (the ARAS drives cortical desynchronization)
    - Sleep-wake switching (the VLPO <-> monoaminergic flip-flop)
    - REM/NREM oscillation (the pontine REM-on/REM-off oscillator)
    - PGO wave generation (ponto-geniculo-occipital bursts that
      drive dream imagery)
    - Neuromodulator sourcing (the nuclei that produce the
      projections modeled in ``neurochemical/``)
    - Parasomnias (arousal-system boundary failures — acting out
      dreams, sleep talking)

Neuromodulator source nuclei (the factories behind
``neurochemical/``):

    Nucleus                        Chemical        Projected to
    -----------------------------  --------------  ------------------
    Locus coeruleus (pons)         Norepinephrine  entire cortex
    Dorsal/median raphe            Serotonin       cortex, forebrain
    VTA, substantia nigra (midbr.) Dopamine        striatum, PFC
    Pedunculopontine/laterodorsal  Acetylcholine   relay, cortex
    Tuberomammillary (hypothal.)   Histamine       cortex
    Basal forebrain (not autonomics) Acetylcholine  cortex, hippocampus

The hypothalamic components of the sleep circuit (VLPO, orexin,
suprachiasmatic nucleus) are anatomically diencephalic, but the
sleep-wake switch is functionally one circuit spanning hyporelay
and autonomics — it is documented here as a unit.


════════════════════════════════════════════════════════════════════════
MATHEMATICAL FOUNDATION: THE SLEEP-WAKE FLIP-FLOP
════════════════════════════════════════════════════════════════════════

Saper's circuit model (Saper, Scammell & Lu, Nature 2005) observes
that wake-promoting monoaminergic nuclei (MA: LC, raphe, TMN) and
the sleep-promoting ventrolateral preoptic area (VLPO) mutually
inhibit each other. Each side, by inhibiting the other, disinhibits
itself — an electronic flip-flop. This produces two stable states
(wake, sleep) with fast transitions and few intermediate states.

The quantitative formulation is the Phillips–Robinson model
(Phillips & Robinson, J. Biol. Rhythms 2007; Fulcher, Phillips &
Robinson, PLOS ONE 2010 for the orexin extension). Population mean
firing rates V_m (monoaminergic) and V_v (VLPO) obey:

    τ_v dV_v/dt + V_v = F( -ν_vm V_m + D )
    τ_m dV_m/dt + V_m = F( -ν_mv V_v + ν_orx Q_orx )

where the firing-rate response is the sigmoid

    F(x) = Q_max / (1 + exp( -(x - θ) / σ' ))

    τ       ~ 10 s (VLPO) / ~10 s (MA) population time constants
    ν_vm    VLPO <- MA inhibitory gain
    ν_mv    MA <- VLPO inhibitory gain
    D       circadian + homeostatic sleep drive afferent to VLPO
    ν_orx   orexinergic (lateral hyporelay) excitation onto MA —
            the stabilizer. Loss of orexin shrinks the hysteresis
            loop: the model falls through the switch repeatedly,
            reproducing narcolepsy (Fulcher et al. 2014).

Model behaviors replicated:
    - Hysteresis: a bistable region where wake and sleep coexist;
      the switch only flips when the drive pushes past the fold.
    - Sleep inertia: the orexin-stabilized lag between the switch
      flipping and full cortical arousal.
    - Narcolepsy: reduced mutual inhibition -> frequent unwanted
      transitions, reduced waking arousal.


════════════════════════════════════════════════════════════════════════
MATHEMATICAL FOUNDATION: THE REM OSCILLATOR
════════════════════════════════════════════════════════════════════════

Within sleep, the NREM/REM alternation is generated by a second
autonomics switch in the pons. The classical model is the
McCarley–Hobson reciprocal interaction (Science 1975): REM-on
pontine reticular giant cells (FTG) and REM-off locus coeruleus
neurons form a predator-prey pair obeying Lotka–Volterra dynamics:

    dR/dt = a R - b R O        REM-on  (self-exciting, inhibited by O)
    dO/dt = -c O + d R O       REM-off (recruited by R, then decays)

The nonlinear interaction term R·O produces a limit cycle whose
period approximates the ~90-minute ultradian sleep-cycle rhythm.

The extended model — the Limit Cycle Reciprocal Interaction Model
(LCRIM, McCarley & Massaquoi, Am. J. Physiol. 1986; J. Sleep Res.
1992) — adds:

    - Excitatory input E that arrests the oscillator during wake
      (E acts on REM-off neurons, indirectly suppressing REM-on).
    - Circadian-phase-dependent entry point into the limit cycle,
      which reproduces the observed lengthening and intensification
      of successive REM periods across the night.
    - Integration with the two-process model's homeostatic
      slow-wave-activity regulation (Borbély).

Modern refinement (Lu et al., Nature 2006): the REM switch itself
is another flip-flop — SLD (sublaterodorsal) REM-on neurons vs
vlPAG/LPT REM-off neurons, mutually inhibitory, with orexin and
monoaminergic tone biasing the balance.


════════════════════════════════════════════════════════════════════════
PGO WAVES
════════════════════════════════════════════════════════════════════════

Ponto-geniculo-occipital waves are phasic bursts generated in the
pons that propagate through the lateral geniculate nucleus (the
thalamic visual relay — see ``relay/``) to the occipital cortex.
They precede and accompany REM sleep and are associated with the
visual imagery of dreams. Each wave is a discrete event: a pontine
burst, a thalamic relay spike, a cortical response.


════════════════════════════════════════════════════════════════════════
ANATOMICAL BOUNDARIES
════════════════════════════════════════════════════════════════════════

    - Hyporelay (documented under ``affect/``): the VLPO,
      orexin, and SCN halves of the sleep-wake switch live there
      anatomically; the circuit is documented here as a unit.
    - Thalamus (``relay/``): the ARAS projects to cortex via the
      relay; sleep spindles and K-complexes are thalamocortical.
    - All subsystems: every cortical area depends on autonomics arousal.
      Sleep is a global state change driven from below.


════════════════════════════════════════════════════════════════════════
MODULE ORGANIZATION
════════════════════════════════════════════════════════════════════════

The autonomics's modules are multi-subsystem by nature — arousal and sleep
state affect every region — so they stay at the top level and are
re-exported here. The pattern follows ``association``:

    from genesis_cognitive.autonomics import SleepCycleTracker

Re-exported modules:

    (sleep package — the autonomics-controlled state machinery)

    SleepStage
        The five arousal states (WAKE, N1, N2, N3, REM) — the output
        of the flip-flop switches.

    SleepCycleTracker
        The N1 -> N2 -> N3 -> N2 -> REM ultradian progression — the
        implemented analogue of the LCRIM limit cycle: stage
        transitions driven by time-in-stage and cycle number, with
        REM periods lengthening across the night (as the LCRIM's
        circadian entry-point variation predicts).

    SleepInertia
        The orexin-stabilization lag — residual impairment after the
        wake flip, decaying on the orexin timescale.

    HypnagogicState
        The N1 transition — the flip-flop mid-flip: mixed imagery,
        intrusions, hypnic phenomena while the switch completes.

    PGOWave
        Pontine burst events relayed through the relay (LGN) to
        the occipital subsystem — the pontine half of the ponto-
        geniculo-occipital pathway.

    ParasomniaEvent
        Arousal-system boundary failures — incomplete state
        transitions producing sleep talking, partial arousal, or
        dream enactment.

Referenced but not re-exported (documented in their own subsystems):

    (neurochemical/)
        The 18-chemical dynamics live in the Rust daemon and Python
        helper modules. The autonomics *contains* the source nuclei
        (LC, raphe, VTA/SNc, PPT/LDT) — the chemicals' computational
        roles are documented in ``neurochemical/``.

    (sleep/) dream_synthesis.py, inner_life.py, compression.py
        Dream CONTENT synthesis (edge proposal/validation) and
        mind-wandering are cortical — default-mode-network and
        hippocampal-replay processes riding on the state the
        autonomics sets. See auditory (hippocampus) and
        control (mind-wandering / autobiographical content).
"""

from __future__ import annotations

from .._views import view_getattr

# The autonomics's modules are multi-subsystem — they stay at the top
# level / in the sleep package and are lazily re-exported here so the
# anatomy is a real connection layer, not just documentation.
_EXPORTS: dict[str, str] = {
    # The five arousal states — the output of the flip-flop switches
    "SleepStage": "brain_waves",
    # The N1 -> N2 -> N3 -> N2 -> REM ultradian progression — the
    # implemented analogue of the LCRIM limit cycle
    "SleepCycleTracker": "sleep",
    # The orexin-stabilization lag after the wake flip
    "SleepInertia": "sleep",
    # The N1 transition — the flip-flop mid-flip
    "HypnagogicState": "sleep",
    # Pontine bursts relayed through the LGN to occipital cortex
    "PGOWave": "sleep",
    # Arousal-system boundary failures — incomplete transitions
    "ParasomniaEvent": "sleep",
}

__all__ = sorted(_EXPORTS)

__getattr__ = view_getattr(_EXPORTS, __name__)
